<?php
global $user;
$uri = $_SERVER["REQUEST_URI"];
$index = 0;
if (strpos($uri, 'infovirtualsite')) {
  $index = 1;
} else if (strpos($uri, 'app/sns')) {
  $index = 2;
} else if (strpos($uri, 'fileshare')) {
  $index = 3;
} else if (strpos($uri, 'tongxunluvirtualsite')) {
  $index = 4;
}
$enabledApps = isset($setting->data) && isset($setting->data['apps']) ? $setting->data['apps'] : array();
?>
<div id="page-top" class="top" style="position:relative;z-index: 200;">
  <div class="topLogin">
    <div class="topLoginL">
      <a href="<?php echo url('default/home')?>">进入云门户</a>
      <?php if ($is_admin) :?>
      <a href="<?php echo url($this->getUrl('settings'), true);?>">专业门户管理</a>
      <?php endif;?>
    </div>
<?php if (isLogin()): ?>
    <div class="topLoginR">
      <span id="header-clock" style="margin-right:10px"><?php echo date('Y-m-d G:i', REQUEST_TIME) ?></span>
      <a href="<?php echo url('desktop') ?>"><?php echo $this->plain($user->userName) ?></a> |
      <?php echo $this->plain($user->desc) ?> |
      <a href="<?php echo url('user/logout') ?>">退出</a>
    </div>
<?php else: ?>
    <div class="topLoginR"><a href="<?php echo url('user/login') ?>">登录</a></div>
<?php endif ?>
  </div>
  <div class="topLogo">
    <div class="LogoIcon"><a href="#"></a></div>
    <div class="LogoIconR "><span class="siteTitle"><?php echo $title;?></span></div>
  </div>
  <div class="topMenu">
    <a href="<?php echo url($this->getUrl('')) ?>"<?php if($index==0){?> class="topMenuOn"<?php } ?>>首页</a>
<?php if (in_array('unisxinxifabu', $enabledApps)): ?>
    <a href="<?php echo url($this->getUrl('call/unisxinxifabu/0/publishsite/infovirtualsite/indexlist')) ?>"<?php if($index==1){?> class="topMenuOn"<?php } ?>>专业信息</a>
<?php endif ?>
<?php if (in_array('sns', $enabledApps)): ?>
    <a href="<?php echo url($this->getUrl('app/sns')) ?>"<?php if($index==2){?> class="topMenuOn"<?php } ?>>专业论坛</a>
<?php endif ?>
<?php if (in_array('fileshare', $enabledApps)): ?>
    <a href="<?php echo url($this->getUrl('fileshare')) ?>"<?php if($index==3){?> class="topMenuOn"<?php } ?>>文档下载</a>
<?php endif ?>
<?php if (in_array('unisapptongxunlu', $enabledApps)): ?>
    <a href="<?php echo url($this->getUrl('call/unisapptongxunlu/0/publishsite/tongxunluvirtualsite/index/?type=virtualsite')) ?>"<?php if($index==4){?> class="topMenuOn"<?php } ?>>专业通讯录</a>
<?php endif ?>
  </div>
  <div class="topLine"></div>
</div>