<?php echo $header;?>
<script type="text/javascript">
var menuitem = '<?php echo $menuitem ?>';
</script>
<link href="<?php echo $tplPath?>/css/default_template.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $tplPath?>/css/app_department.css" rel="stylesheet" type="text/css" />
<div class="content940">
  <div id="department" class="appDepartment">
<?php if ($layout && count($layout)>0) :?>
<?php foreach ($layout as $i => $column): ?>
    <div class="column appDepartment<?php if (($i+1)%2 == 0) {  echo 'R';}else{echo 'L';}?> c<?php echo $i;?>">
<?php
foreach ($column as $block):
  if (!isset($apps[$block[1]])) {
    continue;
  }
  $appInstance = AopApp::getInstance($apps[$block[1]]);
?>
      <div class="block" style="margin:5px 0">
        <div class="cnt">
        <?php
          echo $appInstance->draw($block[2], array('instance' => $instance, 'instance_id' => $instanceId,'owners' => $owners));
        ?>
        </div>
      </div>
<?php endforeach ?>
    </div>
<?php endforeach;?>
<?php endif;?>
</div>
</div>

<?php if ($editable) :?>
<div class="QQbox" id="divQQbox" style="top:100px">
	<div class="OnlineBtn"><a href="<?php echo url($this->getUrl('settings'), true);?>">进入管理页面</a></div>
</div>
<script type="text/javascript">
<!--
lastScrollY = 0;
function FloatScroll() {
    var diffY;
    if (document.documentElement && document.documentElement.scrollTop){
    	diffY = document.documentElement.scrollTop;
	}
    else if (document.body){
    	diffY = document.body.scrollTop;
	}
    else{}
    percent = .1 * (diffY - lastScrollY);
    if (percent > 0){
		percent = Math.ceil(percent);
	}
    else{
		percent = Math.floor(percent);
	}
    document.getElementById("divQQbox").style.top = parseInt(document.getElementById("divQQbox").style.top) + percent + "px";
    lastScrollY = lastScrollY + percent;
}

window.setInterval("FloatScroll()",1);
//-->
</script>
<?php endif;?>
<?php echo $this->render('footer') ?>
