<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESAppClientPublish/css/index.css" />
<script
	type="text/javascript"
	src="<?php echo $tplPath;?>/ESAppClientPublish/js/publish.js"></script>

<div id='ESAppClientPublishIndex' style="width: 700px">
	<div class='publicLeftDiv' id='publicLeftDiv' style="width: 200px">
		<div id='type_all'>
			<a href='javascript:;' class='selected' id='all'>全部</a> <a
				href='javascript:;' id='1'>档案新闻</a> <a href='javascript:;' id='2'>档案故事</a>
			<a href='javascript:;' id='3'>大事记</a> <a href='javascript:;' id='4'>档案规范</a> <a href='javascript:;' id='5'>图说档案</a>
		</div>
	</div>
	<div class='rightDiv' id='rightDiv' style="width: 480px">
		<table id="publish"></table>
	</div>
</div>
