<link href='<?php echo $tplPath?>/ESDefault/css/index.css' rel="stylesheet">
<div class="page">
    	<div class="wrap">
        	<div class="main">
            	<div class="row-2">
                    <ul class="inner-btn" name="userDeskAppsMenu" id = "userDeskAppsMenuId">
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    	<li><a href="#"></a></li>
                    </ul>
                    <div class="clear"></div>
                    <div class="notice-box">
                        <div class="title-bar">
                            <span class="title">档案新闻</span>
                            <a href="#" class="more" id = "ArchiveNews" controller= "ESArchiveNewsMove" action = "index"></a>
                        </div>
                        <div class="clear"></div>
                        <div class="list" id = "ArchiveNewsLists" style="height: 100px ;">
                        </div>
                    </div>
                </div>
                <!--   liuhezeng 20140923 添加自适应样式  -->
            	<div class="row-2-2">
                    <div class="message-task">
                        <div class="title-bar">
                            <span class="title">待办</span>
                            <a href="#" class="more" id = "myTaksListMoreId" controller = "ESCollaborative" action = "index"></a>
                        </div>
                        <ul class="list" id = "preTaskListsContainer">
                        </ul>
                    </div>
                </div>
                <div class="row-1">
                    <ul class="inner-b-btn">
                        <li class="subMoudleFunClickCls" id = "showStandardMove" controller= "ESStandardMove" action = "index" ><a href="#" class="btn1" style = "margin-left:0px;">档案规范</a></li>
		                <li class="subMoudleFunClickCls" id = "showEventMove" controller= "ESEventMove" action = "index"><a href="#" class="btn2">大事记</a></li>
		                <li class="subMoudleFunClickCls" id = "showPicMove" controller= "ESPicMove" action = "index"><a href="#" class="btn3" >图说档案</a></li>
		                <li class="subMoudleFunClickCls" id = "showStoryMove" controller= "ESStoryMove" action = "index"><a href="#" class="btn4" >档案故事</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="menu" >
        	<div class="all" id = "allMenusContainer">
            	<div class="icon">所有功能</div>
                <ul id = "menu" class = "menuUls">
                	<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>1));?>
                </ul>
            </div>
            <div class="items">
            	<ul>
            	
            		<li>
                    	<a href="#" onclick="editMyUserinfo()">
                    	<!-- wanghongchen 20140930  首页显示自定义头像 -->
                            <div class="avatar">
                            	<?php if($iconUrl == null){?>
	                            	<img id="selfIcon" src="<?php echo $tplPath?>/ESDefault/images/avatar.jpg" />
                            	<?php }else{?>
                            		<img id="selfIcon" src="<?php echo $iconUrl?>" />
                            	<?php }?>
                            </div>
                            <span id="mainPageCurUser"><?php echo $GLOBALS['user']->userName;?></span>
                        </a>
                    </li>
                    <li  class = "tasksListCls" controller = "ESCollaborative" action = "index">
                    	<a href="#">
                            <div class="icon i1"><img src="<?php echo $tplPath?>/ESDefault/images/icon_menu_item_1.png"/><em id = "preTasksCounter"></em></div>
                            <span>待办事项</span>
                        </a>
                    </li>
                    <li>
                    	<a href="#" onclick="allMessageDialog()">
                            <div class="icon i2"><img src="<?php echo $tplPath?>/ESDefault/images/icon_menu_item_2.png"/><em id = "preTasksCounter2"></em></div>
                            <span >消息管理</span>
                        </a>
                    </li>
                    <li>
                    	<a href="/setting">
                            <div class="icon i3"><img src="<?php echo $tplPath?>/ESDefault/images/icon_menu_item_3.png"/></div>
                            <span>设置</span>
                        </a>
                    </li>
                    <li onclick = "window.open('<?php echo url('user/logout') ?>','_self')">
                    	<a href="#">
                            <div class="icon i4"><img src="<?php echo $tplPath?>/ESDefault/images/icon_menu_item_4.png"/></div>
                            <span>退出</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>1));?>

<script
	type="text/javascript"
	src="<?php echo $tplPath;?>/public/js/jquery.appclient.js?baseurl=<?php echo $esaction->generateUrl(array());?>"></script>
<script
	type="text/javascript"
	src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<script
	type="text/javascript"
	src='<?php echo $tplPath?>/ESDefault/js/index.js'></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/ztree/js/jquery.ztree.excheck.min.js"></script>
	
<script
	type="text/javascript"
	src='<?php echo $tplPath?>/ESDefault/js/pagebtn.js'></script>
	<script
	type="text/javascript"
	src='<?php echo $tplPath?>/ESDefault/js/picView.js'></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESOrgAndUser/js/button.js"></script>	
<link href="<?php echo $tplPath?>/ESOrgAndUser/css/style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/ESOrgAndUser/js/ESOrgAndUser.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFormStart/js/formApprovalHandle.js"></script>
<!-- END JAVASCRIPTS picView.js-->
<script type="text/javascript">
	/** xiaoxiong 20140711 自动展现待处理消息界面 **/
	jQuery(document).ready(function(){
		var handler = "<?php echo isset($_POST["handler"])?$_POST["handler"]:'';?>" ;
		if('' != handler){
			eval(handler);
		}
	});
</script>
