<div id="dd">
	<form id="importTagsForm" style="margin: 0;" action="" enctype="multipart/form-data" method="post">
		<div><span>请选择文件:</span><input id="importTagsFile" type="file" name="importTags"/></div>
		<input name="id" type="hidden" value="<?php echo $id;?>">
		<input name="type" type="hidden" value="<?php echo $type;?>">
		<input name="ip" type="hidden" value="<?php echo $ip;?>">
		<input name="userId" type="hidden" value="<?php echo $userId;?>">
	</form>
</div>
