<?php 
	$user = $esaction->exec("getProxy", "user")->getUserInfo($esaction->getUser()->getId())->displayName;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESArchiveLending/css/orgtree.css" />
<div style="width:620px;height:600px;">
    <div>
      <form id="form_add" method="post" action="" enctype="multipart/form-data" style='padding-bottom: 5px; '>
      <input type="hidden" name="submit" value="add"/>
      <input type="hidden" name="readerid" value=""/>
      <input type="hidden" name="deptcode" value=""/>
      <input type='hidden' title="请输入外来借阅人" name="reader">
      <div class="contentDiv" style="width:608px;height:280px;margin:5px 0 5px 0;border:1px solid #ccc;padding:5px; overflow-y:auto;overflow-x:hidden;position:relative;float: left;">
      	<ul>
      		<li class="leftTv">借阅人&nbsp;<font color="red" size="3">*</font></li>
      		<li id="btnIn">
      			<input type="text" value="" title="请输入外来借阅人" name="reader" readonly="readonly"/>
      			<span><img id="btn" title="单击我,可选择系统内借阅人信息" src="<?php echo $tplPath;?>/ESArchiveLending/images/group.png"/></span>
      		</li>
      		<li class="rightTv">单位</li>
      		<li id="dept">
      			<input type="text" value="" name="dept"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">电话</li>
      		<li>
      			<input type="text" value="" name="tel"/>
      		</li>
      		<li class="rightTv">邮箱</li>
      		<li>
      			<input type="text" value="" name="email"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">利用目的&nbsp;<font color="red" size="3">*</font></li>
      		<li>
      			<select name="usepurpose" id="selectSty" style="width:184px;height:23px;line-height:23px;">
					<option value="编史修志">编史修志</option>
					<option value="工作查考">工作查考</option>
					<option value="学术研究">学术研究</option>
					<option value="经济建设">经济建设</option>
					<option value="宣传教育">宣传教育</option>
					<option value="其他">其他</option>
				</select>
      		</li>
      		<li class="rightTv">催还提前天数&nbsp;<font color="red" size="3">*</font></li>
      		<li>
			<input type="text" name="validdate" value="3"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">登记人&nbsp;<font color="red" size="3">*</font></li>
      		<li>
      			<input type="text" value="<?php echo $user?>" name="register" readonly="readonly"/>
      		</li>
      		<li class="rightTv">登记日期&nbsp;<font color="red" size="3">*</font></li>
      		<li>
      			<input type="text" id='times' readonly='readonly' value="<?php echo date("Y-m-d");?>" name="registdate"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">状态&nbsp;<font color="red" size="3">*</font></li>
      		<li>
      			<input type="text" value="未提交" readonly="readonly" name="status"/>
      		</li>
      		<li class="rightTv">身份证</li>
      		<li>
      			<input type="text" value="" name="identity" />
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">备注</li>
      		<li>
      			<textarea style="resize:none;text-indent:2px;width:488px;height:50px;font-size:12px;font-family:Arial, Helvetica, sans-serif, 宋体" name="description"></textarea>
      		</li>
      	</ul>
     <?php 
     if(isset($data)){
     	for($i =0 ;$i<count($data);$i++){
     		if($data[$i]['type']=='TEXT' || $data[$i]['type']=='NUMBER' || $data[$i]['type']=='FLOAT'){
	     		if($i%2==0) echo '<ul>';
	     		echo '<li class=';
	     		if($i%2==0){
	     			echo '"leftTv" >'.$data[$i]['field'].'</li>';
	     		}else{
	     			echo '"rightTv" >'.$data[$i]['field'].'</li>';
	     		}
	     			echo '<li>
	      					<input type="text"  name="c'.$data[$i]['id'].'" id = "c'.$data[$i]['id'].'"/>
	      				</li>';
	     		if($i%2==1)  echo '</ul>';
     			
     		}else if($data[$i]['type']=='BOOLEAN'){
     			if($i%2==0) echo '<ul>';
     			echo '<li class=';
     			if($i%2==0){
     				echo '"leftTv" >'.$data[$i]['field'].'</li>';
     			}else{
     				echo '"rightTv" >'.$data[$i]['field'].'</li>';
     			}
     			echo '<li>
     				<select style="width:184px;height:23px;line-height:23px;" name="c'.$data[$i]['id'].'" id = "c'.$data[$i]['id'].'">
     					<option value="2">否</option>
     					<option value="1">是</option>
     				</select>
     			</li>';
     			if($i%2==1)  echo '</ul>';
     		}else if(isset($data[$i]['propValue'])){
     			if($i%2==0) echo '<ul>';
     			echo '<li class=';
     			if($i%2==0){
     				echo '"leftTv" >'.$data[$i]['field'].'</li>';
     			}else{
     				echo '"rightTv" >'.$data[$i]['field'].'</li>';
     			}
     			echo '<li>
     			<select style="width:184px;height:23px;line-height:23px;" name="c'.$data[$i]['id'].'" id = "c'.$data[$i]['id'].'">';
     			echo '<option value="">--请选择--</option>';
     			for($t =0 ;$t<count($data[$i]['propValue']);$t++){
     				echo '<option value="'.$data[$i]['propValue'][$t]['identifier'].'">'.$data[$i]['propValue'][$t]['title'].'</option>';
     			}
     				
     			echo '</select>
     			</li>';
     			if($i%2==1)  echo '</ul>';
     		}else if($data[$i]['type']=='DATE'){
     			if($i%2==0) echo '<ul>';
     			echo '<li class=';
     			if($i%2==0){
     				echo '"leftTv" >'.$data[$i]['field'].'</li>';
     			}else{
     				echo '"rightTv" >'.$data[$i]['field'].'</li>';
     			}
     			echo '<li>
     			<input type="text" class="Wdate" verify="date/20/0/0" name="c'.$data[$i]['id'].'" id = "c'.$data[$i]['id'].'"/>
     			</li>';
     			if($i%2==1)  echo '</ul>';
     		}else if($data[$i]['type']=='TIME'){
     			if($i%2==0) echo '<ul>';
     			echo '<li class=';
     			if($i%2==0){
     				echo '"leftTv" >'.$data[$i]['field'].'</li>';
     			}else{
     				echo '"rightTv" >'.$data[$i]['field'].'</li>';
     			}
     			echo '<li>
     			<input type="text" class="Wdate1" verify="00:00:00" name="c'.$data[$i]['id'].'" id = "c'.$data[$i]['id'].'"/>
     			</li>';
     			if($i%2==1)  echo '</ul>';
     		}
     	}
     	
     }
     
     
     ?>
      </div>
      </form>
	  <div class="bottom" >
		<table id="borrowDetails"></table>
	  </div>
	</div>
<script type="text/javascript">
   var data =  eval( '<?php echo json_encode($data) ?>');
   for(var i=0;i<data.length;i++){
	   var id = data[i].id;
	   if(data[i].type== 'TEXT'){
		   var l1 = parseInt(data[i].length);
		   var isNull = data[i].isNull;
		   $("#c"+id).attr('l1',l1);
		   $('#c' +id).attr('isNull',isNull);
		   $("#c"+id).blur(function(){
			   var id = this.id;
			   var l1 =  $(this).attr('l1');
			   var isNull = $(this).attr('isNull');
			   var length  = $("#"+id).val().length;
				if( isNull == 1 &&　 $("#"+id).val()==''){
					$("#"+id).addClass("invalid-text").attr("title","此项不能为空");
					return false;
				}else if(length > l1){
					$("#"+id).addClass("invalid-text").attr("title","该输入输入项的长度限制在"+parseInt(l1/2)+"个汉字以内");
					return false;
					}
				$(this).removeClass("invalid-text").attr("title","");
			   });
			
	   }else if(data[i].type=='NUMBER'){
		   var reg=/^[0-9]*$/;
		   var l1 = parseInt(data[i].length);
		   var isNull = data[i].isNull;
		   $("#c"+id).attr('l1',l1);
		   $('#c' +id).attr('isNull',isNull);
		   $("#c"+id).blur(function(){
			   var id = this.id;
			   var l1 =  $(this).attr('l1');
			   var isNull = $(this).attr('isNull');
			   var length  = $("#"+id).val().length;
			   if(!reg.test(this.value) && (this.value!='')){
			   		$("#"+id).val('');
					return false;
			   }else if( isNull == 1 &&　 $("#"+id).val()==''){
					$("#"+id).addClass("invalid-text").attr("title","此项不能为空");
					return false;
				}else if(length > l1){
					$("#"+id).addClass("invalid-text").attr("title","该输入输入项的长度限制在"+l1+"个数字以内" );
					return false;
					}
			   $(this).removeClass("invalid-text").attr("title","");
		   });
	   }else if(data[i].type== 'FLOAT'){
		   var l1 = data[i].length;
		   var l2 = data[i].doLength;
		   var isNull = data[i].isNull;
		   var s = "";
		   for(var t=0;t<parseInt(l1-l2);t++){
				s +="X";
			   }
		   for(var t=0;t<parseInt(l2);t++){
			   if(t==0){
				   s +=".";
			   } 
				s +="X";
		   }
		   $("#c"+id).attr('l1',l1);
		   $("#c"+id).attr('l2',l2);
		   $("#c"+id).attr('s',s);
		   $('#c' +id).attr('isNull',isNull);
		   $("#c"+id).blur(function(){
			   var id = this.id;
			   var l1 =  $(this).attr('l1');
			   var l2 = $(this).attr('l2');
			   var s = $(this).attr('s');
			   var isNull = $(this).attr('isNull');
			   var str="/^[0-9]{1,"+(parseInt(l1)-parseInt(l2))+"}(\\.[0-9]{1,"+l2+"}){0,1}$/";
			   str = str.replace(/\/\//g,"\/");
			   var reg = eval(str);
			   if(!reg.test(this.value) && (this.value!='')){
			   		$("#"+id).addClass("invalid-text").attr("title",'输入值非法！正确格式：'+ s);
					return false;
			   }else if( isNull == 1 &&　 $("#c"+id).val()==''){
					$("#"+id).addClass("invalid-text").attr("title","此项不能为空");
					return false;
						}
				if(parseInt(l2)>0){
					if(this.value.indexOf(".")>0){
						var v = this.value;
						var tg = this.value.split('.')[1].length;
						for(var t= 0;t<(parseInt(l2)-tg);t++){
							v += '0';
						}
						$("#"+id).val(v);
					}else{
						var v = (this.value!=''?this.value:'0')+'.';
						for(var t= 0;t<l2;t++){
							v += '0';
						}
					$("#"+id).val(v);
					}
				}
			   $(this).removeClass("invalid-text").attr("title","");
		   });
		}else{
			  var isNull = data[i].isNull;
			   $('#c' +id).attr('isNull',isNull);
			  $("#c"+id).blur(function(){
				  var id = $(this).attr('id');
			   var isNull = $(this).attr('isNull');
				if( isNull == 1 &&　 $("#"+id).val()==''){
					$("#"+id).addClass("invalid-text").attr("title","此项不能为空");
					return false;
				}else{
					$(this).removeClass("invalid-text").attr("title","");
				}
			   });
			}
			
	 }
	$('.Wdate').die().live('click', function (){WdatePicker({dateFmt:'yyyy-MM-dd'});});
	$('.Wdate1').die().live('click', function (){WdatePicker({dateFmt:'HH:mm:ss'});});
	$(function(){
		$("input[name='tel']").keyup(function(){
			var regTel=/^((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})$))$/g;
			if((!regTel.test(this.value))&&(this.value!='')){
				$("input[name='tel']").addClass("invalid-text").attr("title","请输入合法的电话号码");
				return false;
			}
			$(this).removeClass("invalid-text").attr("title","");
		});
		$("input[name='email']").keyup(function(){
			var regEmail=/^[\w]+([-.][\w]+)*@[\w]+([-.]\w+)*\.[\w]+(\.[\w]+)?$/;
			if((!regEmail.test(this.value))&&(this.value!='')){
				$("input[name='email']").addClass("invalid-text").attr("title","请输入合法的邮箱");
				return false;
			}
			$(this).removeClass("invalid-text").attr("title","");
		});
		$("input[name='validdate']").keyup(function(){
			var reg=/^[1-9]\d*$/;
			if(!reg.test(this.value)){
				$("input[name='validdate']").addClass("invalid-text").attr("title","此项不能为空且只能输入大于零的数字");
				return false;
			}else if(this.value > 30){
				$("input[name='validdate']").addClass("invalid-text").attr("title","借出天数不能超过30天");
				return false;
			}
			$(this).removeClass("invalid-text").attr("title","");
		});

		/**   liuhezeng 20140929 添加备注长度验证 **/
		$("textarea[name='description']").keyup(function(){
			if(getByteLen($(this).val())>200){
				$(this).addClass("invalid-text").attr("title","备注的最大长度为100个汉字！");
				return false;
			}
			$(this).removeClass("invalid-text").attr("title","");
		});
		
		/*$("select[name='select']").change(function(){
			$("input[name='validdate']").removeClass("invalid-text").attr("title","");
		});*/
		//单位点击事件触发focus/click
			var $inside = '<?php echo $inside;?>';
			if($inside == 'false'){
				$('input[name="identity"]').blur(function(){
					var reg=/^((\d{18})|(\d{17}[X])|(\d{17}[x]))*$/;
					if(!reg.test($('input[name="identity"]').val())){
						$('input[name="identity"]').addClass("invalid-text").attr("title","请输入合法的身份证号");
					}else if($('input[name="identity"]').val() == null || $('input[name="identity"]').val()==''){
						$('input[name="identity"]').addClass("invalid-text").attr("title","此项不能为空");	
					}else{
						$('input[name="identity"]').removeClass("invalid-text").attr("title","");
					}
				});
				$('input[name="reader"]').removeAttr("readonly");
			}
		var foo=function(){
			var content = [];
			if($inside == 'true'){
				/**
				content.push("<table>");
				content.push("<tr>");
				content.push("<td>");
				content.push("<div id='orgtreebox' style='width:200px; height:350px;overflow:auto;'><ul id='orgtree' class='ztree'></ul></div>");
				content.push("</td>");
				content.push("<td>");
				content.push("<div id='personlistbox' style='height:350px;overflow:auto;'>");
				content.push("<table id='personlist'></table>");
				content.push("</div>");
				content.push("</td>");
				content.push("</tr>");
				content.push("</table>");
				**/
				content.push("<div id='personlistbox' style='height:373px;overflow:auto;'>");
				content.push("<table id='personlist'></table>");
				content.push("</div>");
			}else{
				content.push("<div id='personlistbox' style='height:373px;overflow:auto;'>");
				content.push("<table id='personlist'></table>");
				content.push("</div>");
				
			}
			$.dialog({
				title:'选择借阅人',
	    		width: 550,
	    	   	height: 373,
	    	   	padding: '0px',
	    	    fixed:true,
	    	    resize: false,
	    		content:content.join(""),
	    		cancelVal: '取消',
	    		cancel: true,
	    		okVal: '保存',
	    		ok: function(){
		    		if($inside == 'true'){
		    			// 填入单位和借阅人信息
			    		var radioId = $("#personlist").find("input:checked").attr('id');
						if(radioId=='' || radioId==undefined){
							$.dialog.notice({title:'操作提示',icon:'warning',content:'请选择单位下的借阅人！'});
							return false;
						}
						var listId=radioId.split('|');
						$("input[name='readerid']").val(listId[0]);
						$("input[name='deptcode']").val(listId[1]);
						var radioName = $("#personlist").find("input:checked").attr('value');
						var list=radioName.split('|');
						$("input[name='reader']").val(list[0]);
						$("#dept input[name='dept']").val(list[1]);
						$("input[name='tel']").val(list[2]);
						$("input[name='email']").val(list[3]);
						
			    		this.close();
			    		IreaderD=1;
			    		$("input[name='reader']").removeClass("invalid-text").attr({"title":""});
			    		return false;
		    		}else{
		    			var radioId = $("#personlist").find("input:checked").val();
						if(radioId=='' || radioId==undefined){
							$.dialog.notice({title:'操作提示',icon:'warning',content:'请选择单位下的借阅人！'});
							return false;
						}
						var listId=radioId.split('|');
						$("input[name='readerid']").val(-1);
						$("input[name='deptcode']").val(listId[2]);
						var radioName = $("#personlist").find("input:checked").attr('value');
						var list=radioName.split('|');
						$("input[name='reader']").val(list[1]);
						$("input[name='dept']").val(list[2]);
						$("input[name='identity']").val(list[3]);
						$("input[name='tel']").val(list[4]);
						$("input[name='email']").val(list[5]);
						$("input[name='identity']").attr('readonly','true');
						
			    		this.close();
			    		IreaderD=1;
			    		$("input[name='reader']").removeClass("invalid-text").attr({"title":""});
			    		return false;
		    		}
		    	},
				init:initSelectOrg
	    	});
		};
		$("#btnIn img").bind("click",foo);
		$("input[name='reader']").keyup(function(){
			$("#dept input[name='dept']").val("");
			$("input[name='tel']").val("");
			$("input[name='email']").val("");
			$(this).removeClass("invalid-text").attr("title","您输入的借阅人为外来人员");
			IreaderD=0;
		});
		// 初始化选择单位和借阅人界面
		function initSelectOrg(){
			if($inside == 'true'){
			//	createOrgTree();
				createPersonList();
			}else{
				createTempPerson();
			}
		}
		//临时用户grid列表
		function createTempPerson(){
			$("#personlist").flexigrid({
				url : $.appClient.generateUrl({ESArchiveUsingModel:'getTempUsers',showUser:true},'x'),
				dataType : 'json',
				editable : true,
				colModel : [
				            {display:'操作', name:'cbox',  width:55, align:'center'},
				            {display:'姓名', name:'userName',  width:120, align:'center'},
				            {display:'单位', name:'dep',  width:120, align:'center'},
				            {display:'身份证号', name:'identity',  width:120, align:'center'},
				            {display:'电话', name:'phone',  width:120, align:'center'},
				            {display:'Email', name:'email',  width:120, align:'center'}
				            ],
				            buttons:[],
				                     singleSelect:true,
				             		usepager : true,
				             		title : '工作流管理',
				             		useRp : true,
				             		rp : 20,
				             		nomsg : "没有数据",
				             		showTableToggleBtn : false,
				             		pagetext : '第',
				             		outof : '页 /共',
				             		width : 550,
				             		height : 266,
				             		pagestat : ' 显示 {from} 到 {to}条 / 共{total} 条' 
			});
			$("#personlist tr").live('click',function(){
				$(this).find('div input').change();
				$(this).find('div input').attr('checked',true);
			});
			$('#personlistbox div[class="tDiv2"]').append('<div class="find-dialog"><input id="queryPersonWord" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="keyWord" value="请输入关键字" /><span id="queryPersonTable"></span></div>');
			$('#personlistbox div[class="tDiv"]').css({"border-top":"1px solid #ccc",'height':'25px'});
		}
		$('#queryPersonTable').die().live('click',function(){
			var keyWord = $('#queryPersonWord').val();
			if(keyWord=='请输入关键字' ){
				keyWord = '';
			}
			if($inside == 'true'){
				$("#personlist").flexOptions({url:$.appClient.generateUrl({ESArchiveLending:'getUserList'},'x'),newp:1,query:{keyWord:keyWord}}).flexReload();
			}else{
				$("#personlist").flexOptions({url:$.appClient.generateUrl({ESArchiveUsingModel:'getTempUsers'},'x'),newp:1,query:{keyWord:keyWord}}).flexReload();
			}				
		});
		// 创建机构树目录
		function createOrgTree(){
			var setting = {
					view: {
						dblClickExpand: false,
						showLine: false
					},
					data: {
						simpleData: {
							enable: true
						}
					},
					async: {
						enable: true,
						dataType: 'json',
						url: $.appClient.generateUrl({ESArchiveLending:'getSubOrg1'},'x'),
						autoParam: ["id"]
					},
					callback: {
						onClick : nodeClick
					}
				};
				function nodeClick(event, treeId, treeNode){
					zTree = $.fn.zTree.getZTreeObj("orgtree");
					zTree.expandNode(treeNode);
					$("#personlist").flexOptions({url:$.appClient.generateUrl({ESArchiveLending:'getUserList',orgid:treeNode.id},'x')}).flexReload();	
				};
				var url = $.appClient.generateUrl({ESArchiveLending:'initOrg'},'x');
				$.ajax({
					url:url,
					dataType: 'json',
					success:function(nodes){
						$.fn.zTree.init($("#orgtree"), setting, nodes);
						$("#orgtree_1_span").click();
					},
					cache:false
				});
		};
		// 显示人员列表
		function createPersonList(){
			$("#personlist").flexigrid({
				url:$.appClient.generateUrl({ESArchiveLending:'getUserList',showUser:true},'x'),
				dataType: 'json',
				editable: true,
				colModel : [
					{display: '操作', name : 'id2', width : 40, align: 'center'},
					{display: '姓名', name: 'c1',  width : 68, align: 'center'},
					{display: '联系电话', name: 'c2',width:110,align:'center'},
					{display: '邮箱', name: 'c3',width:120,align:'center'},
					{display: '所属机构', name: 'c4', width:100,align:'center'}
				],
				buttons:[],
				usepager: true,
				rp: 50,
				useRp: true,
				width : 550,
         		height : 266
			});
			$("#personlist tr").live('click',function(){
				$(this).find('div input').change();
				$(this).find('div input').attr('checked',true);
			});
			$('#personlistbox div[class="tDiv2"]').append('<div class="find-dialog"><input id="queryPersonWord" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="keyWord" value="请输入关键字" /><span id="queryPersonTable"></span></div>');
			$('#personlistbox div[class="tDiv"]').css({"border-top":"1px solid #ccc",'height':'25px'});
		}
		//借阅明细全选按钮
		$("input[name='ids3']").die().live('click',
			function(){
				$("input[name='id3']").attr('checked',$(this).is(':checked'));
			}
		);
		//添加借阅明细查看
		var __colMol=[
			{display: '序号', name : 'num', width : 40, align: 'center',metadata:'num'}, 
			{display: '<input type="checkbox" name="ids3" id="">', name : 'id3', width : 40, align: 'center'},
			{display: '档号', name : 'c3', width : 60,align: 'left',metadata:'ArchivalCode'},
			{display: '题名', name: 'c4',width : 80,align: 'left',metadata:'Summary'},
			{display: '借阅类型', name: 'c5',width : 183,align: 'left',metadata:'type'},
			{display: '状态', name: 'c6',width : 50,align: 'center',metadata:'status'},
			{display: '发生日期', name: 'c8',width : 60,align: 'center',metadata:'date'},
			{display: '应归还日期', name: 'shouldReturnDate',width : 60,align: 'center',metadata:'shouldReturnDate'},
			{display: '归还日期', name: 'c12',width : 60,align: 'center',metadata:'RETURN_DATE'},
			{display: '卷数', name: 'c9',width : 90,align: 'center',metadata:'fileCount'},
			{display: '件数', name: 'c10',width : 90,align: 'center',metadata:'innerFileCount'},
			{display: '是否改变颜色', name : 'changeColor', width : 120, sortable : true, align: 'center',metadata:'changeColor',hide:true},
			{display: 'path', name: 'path',width : 90,align: 'center',metadata:'path',hide:true},
			{display: 'idParent', name: 'idParent',width : 90,align: 'center',metadata:'idParent',hide:true},
			{display: '备注', name: 'c7', width :90,align: 'center',metadata:'mark'}
		];
		for(var i = 0;i<storeFiled.length;i++){
			__colMol.push({display:storeFiled[i].field,name:'d'+storeFiled[i].id,width:80,sortable : true, align: 'center',metadata:'d'+storeFiled[i].id});
		}
		$("#borrowDetails").flexigrid({
			url:false,
			dataType: 'json',
			editable: true,
			colModel :__colMol,
			buttons : [
				{name: '选择系统档案', bclass: 'add',onpress:addDetails},
				{name: '手工录入', bclass: 'add',onpress:addLineDetail},
				{name: '删除', bclass: 'delete',onpress:delDetails}
			],
			title: '借阅明细列表',
			showTableToggleBtn: false,
			width: 620,
			height: 210
		});
		$('.bottom div[class="tDiv2"]').prepend('<span style="float:left;margin:2px 0px 3px 5px ;padding-right:3px;border-right:1px solid #ccc;">利用库数据</span>');
		$('.bottom div[class="tDiv"]').css("border-top","1px solid #ccc");
		
		function addDetails(){
			var url=$.appClient.generateUrl({ESArchiveLending:'record'},'x');
			$.ajax({
			    url:url,
			    success:function(data){
			    var linkdialog=$.dialog({
				    	title:'添加借阅明细',
				    	width: '800px',
				    	height:'380px',
				    	padding:'0px',
			    	   	fixed:  true,
			    	    resize: false,
			    	    okVal:'保存',
					    ok:true,
					    cancelVal: '取消',
					    cancel: true,
				    	content:data,
				    	ok:function()
				    	{
							linkBorrowDetail();
							return false;
						 },
						 init:createFileTree
				    });
			    	// 挂接借阅文件信息
					function linkBorrowDetail(){
						var ACode='';
						var title='';
						var files = [];
						var detailsOtherValue = [];
						var checkboxs = $("#borrowlist").find("input[name='path']:checked");
						if (checkboxs.length > 0 ){
							var types=[];
							var voidTypes='';
							var nums='';
							var paths = [];
							//根据元数据获取相应的标题top
							var ACodeName='';
							var ACodeMeta='';
							var titleName='';
							var titleMeta='';
							var idParent = 'idParent';
							ACodeMeta='ArchivalCode';
							titleMeta='Title';
							ACodeName=$("#borrowlist").flexGetColumnDisplay(['ArchivalCode']);
							titleName=$("#borrowlist").flexGetColumnDisplay(['Title']);
							//根据元数据获取相应的标题top
							var trs=$("#borrowDetails").find("input[name='id3']");
							var metadataValue = [];
							nums=trs.length;
							
							if(trs.length==0){
								$(".bottom").html('<table id="borrowDetails"></table>');
								var _colMol = [
												{display: '序号', name : 'num', width : 40, align: 'center',metadata:'num'}, 
												{display: '<input type="checkbox" name="ids3" id="">', name : 'id3', width : 40, align: 'center'},
												{display: '档号', name : 'c3', width : 60,align: 'left',metadata:ACodeMeta},
												{display: '题名', name: 'c4',width : 80,align: 'left',metadata:titleMeta},
												{display: '借阅类型', name: 'c5',width : 183,align: 'left',metadata:'type'},
												{display: '状态', name: 'c6',width : 50,align: 'center',metadata:'status'},
												{display: '发生日期', name: 'c8',width : 60,align: 'center',metadata:'date'},
												{display: '应归还日期', name: 'shouldReturnDate',width : 60,align: 'center',metadata:'shouldReturnDate'},
												{display: '是否改变颜色', name : 'changeColor', width : 120, sortable : true, align: 'center',metadata:'changeColor',hide:true},
												{display: '归还日期', name: 'c12',width : 60,align: 'center',metadata:'RETURN_DATE'},
												{display: '卷数', name: 'c9',width : 90,align: 'center',metadata:'fileCount'},
												{display: '件数', name: 'c10',width : 90,align: 'center',metadata:'innerFileCount'},
												{display: 'path', name: 'path',width : 90,align: 'center',metadata:'path',hide:true},
												{display: 'idParent', name: 'idParent',width : 90,align: 'center',metadata:'idParent',hide:true},
												{display: '备注', name: 'c7', width :90,align: 'center',metadata:'mark'}
										];
								for(var i = 0;i<storeFiled.length;i++){
									_colMol.push({display:storeFiled[i].field,name:'d'+storeFiled[i].id,width:80,sortable : true, align: 'center',metadata:'d'+storeFiled[i].id});
									if(storeFiled[i].metadata != null && storeFiled[i].metadata!= 'undefined' && storeFiled[i].metadata!= ''){
										if($("#borrowlist").flexGetColumnDisplay([storeFiled[i].metadata]) != null && storeFiled[i].metadata != 'undefined' && storeFiled[i].metadata != ''&& $("#borrowlist").flexGetColumnDisplay([storeFiled[i].metadata]).length>0){
											metadataValue.push({md:[storeFiled[i].metadata],fv:'d'+storeFiled[i].id});
										}
									}
								}
								$("#borrowDetails").flexigrid({
										url:false,
										dataType: 'json',
										editable: true,
										colModel :_colMol,
										buttons : [
											{name: '选择系统档案', bclass: 'add',onpress:addDetails},
											{name: '手工录入', bclass: 'add',onpress:addLineDetail},
											{name: '删除', bclass: 'delete',onpress:delDetails}
										],
										title: '借阅明细列表',
										showTableToggleBtn: false,
										width: 620,
										height: 210
									});
									$("#borrowDetails").flexReload();
							}else{
								trs.each(function(){
									var path=$(this).val();
									var bothPath=path.split('|');
									paths.push(bothPath[0]);
									types.push(bothPath[2]);
								});
								paths=paths.join(',');
								voidTypes=types.join('');
							}
							checkboxs.each(function(){
								var trObj=$(this).closest('tr');
								var checkpath = $(this).val();
								if(paths.length>0){
										if (paths.indexOf(checkpath)==-1) {
											 ACode=$("#borrowlist").flexGetColumnValue(trObj,[ACodeMeta]);
				    		         		 title=$("#borrowlist").flexGetColumnValue(trObj,[titleMeta]);
				    		         		var idParentNum=$("#borrowlist").flexGetColumnValue(trObj,[idParent]);
					    					 files.push(ACode+'|'+title+'|'+checkpath+'|'+idParentNum);
					    					 var vstr = "";
					    					 for(var j= 0 ;j<metadataValue.length;j++){
					    						 var dv=$("#borrowlist").flexGetColumnValue(trObj,[metadataValue[j].md]); 
					    						 vstr = vstr +";"+  metadataValue[j].fv+"@|@"+dv;
					    					 }
					    					 detailsOtherValue.push(vstr.substring(1));
										}
								}else{
									 ACode=$("#borrowlist").flexGetColumnValue(trObj,[ACodeMeta]);
		    		         		 title=$("#borrowlist").flexGetColumnValue(trObj,[titleMeta]);
		    		         		var idParentNum=$("#borrowlist").flexGetColumnValue(trObj,[idParent]);
			    					 files.push(ACode+'|'+title+'|'+checkpath+'|'+idParentNum);
			    					 var vstr = "";
			    					 for(var j= 0 ;j<metadataValue.length;j++){
			    						 var dv=$("#borrowlist").flexGetColumnValue(trObj,[metadataValue[j].md]); 
			    						 vstr = vstr +";"+  metadataValue[j].fv+"@|@"+dv;
			    					 }
			    					 detailsOtherValue.push(vstr.substring(1));
								}
							});
							if(files==''){
								$.dialog.notice({title:'操作提示',content:'您添加的数据重复，请重新选择！',icon:'warning',time:3});
								return false;
							}else{
								for(var t=0;t<files.length;t++){
									var i=1;
									var getFile=files[t].split('|');
									var tJson = {'num':++nums,
											'id3':'<input type="checkbox" name="id3" id="" value="'+getFile[2]+'|'+' '+'|'+archiveType+'"/>',
											'c3':getFile[0],
											'c4':getFile[1],
											'c5':'实体',
											'c6':'未借阅',
											'idParent':getFile[3],
											'c9':'0',
											'c10':'1',
											'c7':'<input name="mark" type="text" size="12" value="" placeholder="请填写备注"/>'
										   };
									  var tStr = JSON.stringify(tJson);
									  tStr = tStr.substr(0,tStr.length-1);
									  tStr = DetailsFieldsShow(tStr,nums);
									  tStr +='}';
									  
									$("#borrowDetails").flexExtendData([{
										'id':i++,
										'cell':JSON.parse(tStr)
									}]);
									DetailValueBlur();
									if(detailsOtherValue[t]!=null && detailsOtherValue[t] != undefined && detailsOtherValue[t] != ''){
										for(var j = 0;j<detailsOtherValue[t].split(";").length;j++){
											var vv = detailsOtherValue[t].split(";")[j].split("@|@");
											if($('#'+vv[0]+nums).html().indexOf("option")>0){
												if(null != vv[1] && vv[1] != "" && vv[1] == "是"){
													$('#'+vv[0]+nums).val(1);
												}else{
													$('#'+vv[0]+nums).val(0);
												}
											}else{
												$('#'+vv[0]+nums).val(vv[1]);
											}
											
										}
									}
								}
								linkdialog.close();
							}
						}else{
							$.dialog.notice({title:'操作提示',content:'请选择您要添加的数据！',icon:'warning',time:3});
							return false;
						}
					};
				},
				cache:false
			});
		}
		//去除挂接借阅文件信息
		function delDetails(){
			var checkboxes=$("#borrowDetails").find("input[name='id3']:checked");
			if(checkboxes.length==0){
				$.dialog.notice({content:"请选择要删除的数据！",time:3});
				return;
			}
			$.dialog({
				content:'确认要删除吗?',
				ok:true,
				okVal:'确认',
				cancel:true,
				cancelVal:'取消',
				ok:function(){
					if(checkboxes.length > 0){
						checkboxes.each(function(){
							$(this).closest("tr").remove();
						});
						$("input[name='ids3']").attr("checked",false);
					}
				},
				cache:false
			});
		}
	});

</script>
</div>