<style>

.fileditNew {
	width: 100%;
	height: 115px;
	float: left;
	border-left: 1px solid #ccc;
	border-bottom: 1px solid #ccc;
}

.fileditdivNew {
	width: 250px;
	height: 25px;
	float: left;
	margin-left: 10px;
	padding: 5px 20px 5px 20px;
}

.fileditdivAreaNew {
	width: 250px;
	height: 68px;
	float: left;
	margin-left: 50px;
	padding: 5px 20px 5px 20px;
}

.filednameNew {
	width: 100px;
	line-height: 25px;
	text-indent: 5px;
	float: left;
}

.filedvalueNew {
	width: 100px;
	height: 25px;
	float: left
}

</style>
<div id='tempUser' height="218px" class="showRoleNews1">
	<div class='fileditdivNew'>
		<p class='filednameNew'>  &nbsp;姓名：</p>
		<p class='filedvalueNew'><input class='input'type="text"  id='userName' name="userName" />
	</div>
	<div class='fileditdivNew'>
		<p class='filednameNew'>  &nbsp;单位： </p>
		<p class='filedvalueNew'><input class='input' type='text' id="dep" name="dep" />
	</div>
	<div class='fileditdivNew'>
		<p class='filednameNew'>  &nbsp;身份证号： </p>
		<p class='filedvalueNew'><input class='input' type="text"   id='identity' name="identity"  />
	</div>
	<div class='fileditdivNew'>
		<p class='filednameNew'>  &nbsp;电话： </p>
		<p class='filedvalueNew'><input class='input' type="text"   id='phone' name="phone"  />
	</div>
	<div class='fileditdivNew'>
		<p class='filednameNew'>  &nbsp;Email： </p>
		<p class='filedvalueNew'><input class='input' type="text"   id='email' name="email"  />
	</div>
</div>
<script type="text/javascript">
	$("#userName").blur(function(){
		if($("#userName").val() == null || trim($("#userName").val())==''){
			$("#userName").addClass("invalid-text").attr("title","此项不能为空");	
		}else{
			$("#userName").removeClass("invalid-text").attr("title","");
		}
	});
	$("#dep").blur(function(){
		if($("#dep").val() == null || trim($("#dep").val())==''){
			$("#dep").addClass("invalid-text").attr("title","此项不能为空");	
		}else{
			$("#dep").removeClass("invalid-text").attr("title","");
		}
	});
	$("#identity").blur(function(){
		var reg=/^((\d{18})|(\d{17}[X])|(\d{17}[x]))*$/;
		if((!reg.test(this.value))){
			$("#identity").addClass("invalid-text").attr("title","请输入合法的身份证号");
		}else if($("#identity").val() == null || trim($("#identity").val())==''){
			$("#identity").addClass("invalid-text").attr("title","此项不能为空");	
		}else{
			$("#identity").removeClass("invalid-text").attr("title","");
		}
	});
	$("#phone").blur(function(){
		var regTel=/^((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})$))$/g;
		if((!regTel.test(this.value))){
			$("#phone").addClass("invalid-text").attr("title","请输入合法的电话号码");
		}else if($("#phone").val() == null || trim($("#phone").val())==''){
			$("#phone").addClass("invalid-text").attr("title","此项不能为空");	
		}else{
			$("#phone").removeClass("invalid-text").attr("title","");
		}
	});
	$("#email").blur(function(){
		reg=/^[\w]+([-.][\w]+)*@[\w]+([-.]\w+)*\.[\w]+(\.[\w]+)?$/; 
		if((!reg.test(this.value))){
			$("#email").addClass("invalid-text").attr("title","请输入合法的邮箱");
		}else if($("#email").val() == null || trim($("#email").val())==''){
			$("#email").addClass("invalid-text").attr("title","此项不能为空");	
		}else{
			$("#email").removeClass("invalid-text").attr("title","");
		}
	});
</script>
