
<script type="text/javascript">
			var list = <?php echo $list;?>;
			var temp = new Array();
			var humi = new Array();
			var dateTimeXAxis = new Array(); // longjunhao 20140915 add 使用日期时间作为横坐标
			for(var i=0;i<list.length;i++){
				temp[i] = parseFloat(list[i].temperature);
				humi[i] = parseFloat(list[i].humidity);
				dateTimeXAxis[i] = list[i].date + "<br>" + list[i].time;
			}
			// longjunhao 20140919 add 动态控制 图表的宽度
			var xSize = dateTimeXAxis.length; // 个数
			var len = 50;
			var xWidth = 70;
			xWidth += xSize*len;
			$('#container').css('width', xWidth + 'px');
			var chart;
			$(document).ready(function() {
				chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container',
						defaultSeriesType: 'line'
					},
					colors:[
						'#AA4643',
						'#4572A7',
						'#89A54E',
						'#80699B',
						'#3D96AE',
						'#DB843D',
						'#92A8CD',
						'#A47D7C',
						'#B5CA92'
					],
					title: {
						text: '库房(编号)-<?php echo $code;?>'
					},
					subtitle: {
						text: ''
					},
					xAxis: {
						labels:{
							rotation:-60,
							align: 'right'
						},
// 						categories: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
						categories: dateTimeXAxis
					},
					yAxis: {
						title: {
							text: '温度/湿度(°C)'
						}
					},
					tooltip: {
						enabled: false,
						formatter: function() {
							return '<b>'+ this.series.name +'</b><br/>'+
								this.x +': '+ this.y +'°C';
						}
					},
					legend: {
						shadow:true
					},
					lang:{
						exportButtonTitle:'导出矢量图',
						printButtonTitle:'打印曲线图',
						downloadPNG:'导出PNG图像',
						downloadJPEG:'导出JPEG图像',
						downloadPDF:'导出PDF文件',
						downloadSVG:'导出SVG可缩放向量图形'
					},
					credits:{
						text:'',
						href:'#'
					},
					plotOptions: {
						line:{
							dataLabels: {
								enabled: true
							},
							enableMouseTracking: false
						}
					},
					series:[{
						name: '温度',
						data: temp
					},{
						name: '湿度',
						data: humi
					}]
				});
			});
</script>
<div style="position: relative; overflow-x: auto; overflow-y: no; width:850px; height: 420px">
	<div id="container" style="height:400px; margin: 0 auto"></div>
</div>