
<div class="estopss">
<div class="submit">
<input type="submit" value="返回" />
</div>
</div>
<div class="esmain">
<div class="ldmleft">
<div class="bg">
<img class="img" src="<?php echo $tplPath?>/ESReadingRoom/img/text.gif" />
</div>
</div>
<div class="ldmright">
<div class="right_top">
<div class="title">
<label>电子文件属性</label>
</div>
<div class="intro">
<div><label>文件类别：</label><span>文档</span><label class="extra">文件大小：</label><span>20M</span></div>
<div><label>创建人：</label><span>刘代明</span><label class="extra">修改人：</label><span>刘代明 2012.08.29</span></div>
<div><label>登录IP：</label><span>127.0.0.1</span></div>
<div><label>文件校验：</label><span>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</span></div>
</div>
</div>
<div class="right_center">
<div class="title">
<label>相关文件</label>
</div>
<div class="intro">
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/word_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/word_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/word_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/word_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/word_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/pdf_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="total"><div class="word_img"><img alt="" src="<?php echo $tplPath?>/ESReadingRoom/img/pdf_big.gif" /></div><div class="word"><span>相关文件1</span></div></div>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
</div>
</div>