<link href="<?php echo $tplPath?>/ESArchiveSeache/css/adsearchall.css" rel="stylesheet" type="text/css" />
<script	type="text/javascript" src="<?php echo url('js/jquery.js')?>"></script>
<div class="main">
<div class="search_bar">
<div class="search">
<form name="ss" action="">
<div class="searchfields">
<span>
<input class="keyword" type="text" maxlength="100" name="keyword" />
</span>
</div>
<button class="submit" type="submit">搜 索</button>
</form>
</div>
<div class="advance_s">
<a href="#">高级搜索</a>
</div>
<div class="application" >
<div class="front_sck">
<img style="position:relative;top:7px;padding-left:10px;"alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/app.gif"  />
<img style="position:absolute; left:20px;top:-10px;" src="<?php echo $tplPath?>/ESArchiveSeache/img/triangle.gif" alt="" />
<img style="position:absolute;left:20px;top:-15px;" src="<?php echo $tplPath?>/ESArchiveSeache/img/square.gif" alt="" />
<span  style="position:absolute;left:32px;top:-10px;font-size:18px;color:#fff;font-weight:bold;">1</span>
<span style="line-height:30px;">去提交审批申请</span>
<img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/u120_original.gif"  />
</div>
<div class="bot_content" style="display:none;">
	<div class="cr1"><span style="position:relative;left:10px;">您所申请的档案</span></div>
    <div class="cr2"><img  src="<?php echo $tplPath?>/ESArchiveSeache/img/c2_file.gif"  /><span><a href="#">关于中国联通2004年工作总结与2005年工作安排</a></span><span style="position:relative;left:10px;">删除 </span>
    </div>
    <div class="cr3"><div style="padding-top:20px;padding-right:30px;"><span>共计<em>1</em>份档案</span></div>
    <div style="text-align:center;float:right;line-height:36px;background:url(<?php echo $tplPath?>/ESArchiveSeache/img/c3_bg.gif);height:38px;width:136px;"><span><a href="#">提交申请批准</a></span>
    </div></div>
</div>
<div class="tog"></div>
</div>

</div>

<div class="clear"></div>
<div class="s_param">
<div class="s_name">
搜索
</div>
<div class="s_count">
找到约 2300 条结果 （用时 0.16 秒）
</div>
<div class="clear"></div>
</div>

<div class="leftnav">
<ul>
<li class="param"><a class="k"  href="">所有结果</a></li>
<li><a class="k1"  href="">照片档案</a></li>
<li><a class="k1"  href="">视频档案</a></li>
<li><a class="k1"  href="">音乐档案</a></li>
</ul>

</div>
<div class="right">
<div class="right_content">
<div class="total">
	<div class="unit">
    <div class="unit_title"><div style="float:left;margin-left:10px;"><span style="font-weight:bold;">所属单位</span></div>
    <div class="clear_type">
	<span>清空</span></div>
	<div class="clear"></div>
	</div>
    <div class="unit_total">
    <table>
    <tbody>
    <tr><td><input id="unit_belong1" type="checkbox" /><label for="unit_belong1">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong2" type="checkbox" /><label for="unit_belong2">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong3" type="checkbox" /><label for="unit_belong3">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong4" type="checkbox" /><label for="unit_belong4">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong5" type="checkbox" /><label for="unit_belong5">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong6" type="checkbox" /><label for="unit_belong6">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong7" type="checkbox" /><label for="unit_belong7">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong8" type="checkbox" /><label for="unit_belong8">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong9" type="checkbox" /><label for="unit_belong9">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong10" type="checkbox" /><label for="unit_belong10">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong11" type="checkbox" /><label for="unit_belong11">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong12" type="checkbox" /><label for="unit_belong12">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong13" type="checkbox" /><label for="unit_belong13">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    <tr><td><input id="unit_belong14" type="checkbox" /><label for="unit_belong14">联通总部</label></td><td><input type="checkbox" /><span>北京分公司</span></td></tr>
    </tbody>
    
    </table>
    
    </div>
    </div>
	
</div>
<div class="filetype">
<div class="type_title">
<div style="float:left;margin-left:10px;"><span style="font-weight:bold;">档案类型</span></div>
<div class="clear_type"><span>清空</span></div>
<div class="clear"></div>
</div>
<div class="type_total">
<table>
    <tbody>
    <tr><td><input type="checkbox" /><span>文书档案</span></td><td><input type="checkbox" /><span>科技档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    </tbody>   
    </table>
</div>
</div>


<div class="yearrange">
<div class="year_title">
<div style="float:left;margin-left:10px;"><span style="font-weight:bold;">年度范围</span></div>
<div class="clear_type"><span>清空</span></div>
<div class="clear"></div>
</div>
<div class="year_total">
<table>
    <tbody>
    <tr><td><input type="checkbox" /><span>文书档案</span></td><td><input type="checkbox" /><span>科技档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    </tbody>   
    </table>
</div>
</div>
<div class="takecare">
<div class="care_title">
<div style="float:left;margin-left:10px;"><span style="font-weight:bold;">年度范围</span></div>
<div class="clear_type"><span>清空</span></div>
<div class="clear"></div>
</div>
<div class="care_total">
<table>
    <tbody>
    <tr><td><input type="checkbox" /><span>文书档案</span></td><td><input type="checkbox" /><span>科技档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    <tr><td><input type="checkbox" /><span>会计档案</span></td><td><input type="checkbox" /><span>会计档案</span></td></tr>
    </tbody>   
    </table>
</div>
</div>
<div class="clear"></div>
<div><input  class="confirm"  type="submit" value="确定" /></div>
</div>
<div class="clear"></div>


<div class="searchresults">
<ul>
	<li>
	<div class="result">
		<div class="result_title">
		<a href=""><span class="title">关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知 </span><span class="time">2012-08-21</span></a>	
		</div>
		<div class="d_title">
		<span>文号:中国<em>联通</em>综字[2004]195号</span>
		<span>题名:关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知</span>
		<span>责任者:中国<em>联通</em>集团公司</span>
		</div>
		<div class="d_param">
		<span>保管期限:长期</span><span>密级:公开</span><span>日期:2004-5-24</span><span>页数:16 </span><span>年度:2004</span>
		<span>备注:</span><span>件号:0152 </span><span>所属部门:综合部 </span><span>保管期限标识:2 </span>
		</div>
		<div>
		<span>全宗号:001</span>
		</div>
	
	</div>
	</li>
	
	<li>
	<div class="result">
		<div class="result_title">
		<a href=""><span class="title">关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知 </span><span class="time">2012-08-21</span></a>	
		</div>
		<div class="d_title">
		<span>文号:中国<em>联通</em>综字[2004]195号</span>
		<span>题名:关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知</span>
		<span>责任者:中国<em>联通</em>集团公司</span>
		</div>
		<div class="d_param">
		<span>保管期限:长期</span><span>密级:公开</span><span>日期:2004-5-24</span><span>页数:16 </span><span>年度:2004</span>
		<span>备注:</span><span>件号:0152 </span><span>所属部门:综合部 </span><span>保管期限标识:2 </span>
		</div>
		<div>
		<span>全宗号:001</span>
		</div>
	
	</div>
	</li>
	<li>
	<div class="result">
		<div class="result_title">
		<a href=""><span class="title">关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知 </span><span class="time">2012-08-21</span></a>	
		</div>
		<div class="d_title">
		<span>文号:中国<em>联通</em>综字[2004]195号</span>
		<span>题名:关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知</span>
		<span>责任者:中国<em>联通</em>集团公司</span>
		</div>
		<div class="d_param">
		<span>保管期限:长期</span><span>密级:公开</span><span>日期:2004-5-24</span><span>页数:16 </span><span>年度:2004</span>
		<span>备注:</span><span>件号:0152 </span><span>所属部门:综合部 </span><span>保管期限标识:2 </span>
		</div>
		<div>
		<span>全宗号:001</span>
		</div>
	
	</div>
	</li>
	<li>
	<div class="result">
		<div class="result_title">
		<a href=""><span class="title">关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知 </span><span class="time">2012-08-21</span></a>	
		</div>
		<div class="d_title">
		<span>文号:中国<em>联通</em>综字[2004]195号</span>
		<span>题名:关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知</span>
		<span>责任者:中国<em>联通</em>集团公司</span>
		</div>
		<div class="d_param">
		<span>保管期限:长期</span><span>密级:公开</span><span>日期:2004-5-24</span><span>页数:16 </span><span>年度:2004</span>
		<span>备注:</span><span>件号:0152 </span><span>所属部门:综合部 </span><span>保管期限标识:2 </span>
		</div>
		<div>
		<span>全宗号:001</span>
		</div>
	
	</div>
	</li>
	<li>
	<div class="result">
		<div class="result_title">
		<a href=""><span class="title">关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知 </span><span class="time">2012-08-21</span></a>	
		</div>
		<div class="d_title">
		<span>文号:中国<em>联通</em>综字[2004]195号</span>
		<span>题名:关于董事长和王总裁在2004年中国<em>联通</em>工作会上讲话通知</span>
		<span>责任者:中国<em>联通</em>集团公司</span>
		</div>
		<div class="d_param">
		<span>保管期限:长期</span><span>密级:公开</span><span>日期:2004-5-24</span><span>页数:16 </span><span>年度:2004</span>
		<span>备注:</span><span>件号:0152 </span><span>所属部门:综合部 </span><span>保管期限标识:2 </span>
		</div>
		<div>
		<span>全宗号:001</span>
		</div>
	
	</div>
	</li>
	</ul>
<div class="page">
	<ul>
	<li><a href="">1</a></li>
	<li><a href="">2</a></li>
	<li><a href="">3</a></li>
	<li><a href="">4</a></li>
	<li><a href="">5</a></li>
	<li><a href="">6</a></li>
	<li class="nextpage"><a href="">下一页</a></li>
	</ul>
	</div>
</div>


</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	
	$(".front_sck").mouseover(function(){
		$(this).css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/application.gif')"});
		$(".bot_content").css({display:"block"});
		});
	
	$(".bot_content").mouseover(function(){
		$(".front_sck").css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/or_bg.gif')"});
		$(this).css({display:"block"});
		$(".front_sck").css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/application.gif')"});
	});
		$(".bot_content").mouseout(function(){
		$(".front_sck").css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/or_bg.gif')"});
		$(this).css({display:"none"});
	});
	$(".cr2").mouseover(function(){
		//alert(111);
		$(this).css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/c2_hover.gif')"});
	});
	$(".cr2").mouseout(function(){
		//alert(111);
		$(this).css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/c2_or.gif')"});
	});

});
</script>