<div class="main">
<div class="content">
<div class="left_content">
<div class="lc">
  <div class="left_top">
	<div class="title">
	<span>关于董事长和王总裁在2004年中国联通工作会上讲话通知</span>
	</div>
		<div class="d_title">
		<label>文号:</label>
		<span>中国联通综字[2004]195号</span><label>题名:</label>
		<span>关于董事长和王总裁在2004年中国联通工作会上讲话通知</span>
		<label>责任者:</label>
		<span>中国联通集团公司</span>
		</div>
		<div class="d_param">
		<label>保管期限:</label><span>长期</span><label>密级:</label><span>公开</span><label>日期:</label><span>2004-5-24</span><label>页数:</label><span>16</span><label>年度:</label><span>2004</span>
		<label>备注:</label><label>件号:</label><span>0152</span><label>所属部门:</label><span>综合部</span><label>保管期限标识:</label><span>2 </span>
		</div>
		<div>
		<label></label>
		<span>全宗号:001</span>
		</div>

  </div>
  <div class="left_con">
  
  <div class="o1"><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/word.gif" /> <label>附件一：董事长发言稿</label></div>
  <div class="o2"><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/download.gif" /> <label>下载此电子档案</label></div>
  <div class="o3"><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/store.gif" /> <label>加入收藏夹</label></div>
  <div class="o4"><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/power.gif" /> <label>申请档案权限</label></div>
 
 <div class="clear"></div>
  </div>
</div>
<div class="efile"><span style="font-family:宋体;margin-left:15px;font-size:13px;font-weight:bold;font-style:normal;text-decoration:none;color:#333333;">电子文件显示</span><img style="margin-left:600px;"alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/close.gif"  /> </div>
<div class="document">
<img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/pdf.gif" />
</div>


</div>
<div class="right_content">
<div class="right_ctop">
<div class="ctop_title"><span>电子档案信息</span></div>
<div><span>浏览：265次 </span><span>下载：109次</span></div>
<div><span>文件类型：附件</span></div>
<div><span>文件格式：<img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/word_small.gif"/>doc</span></div>
<div><span>创建者：中国联通</span></div>
<div><span>创建时间：2012-08-24</span></div>
<div><span>文件大小：256k</span></div>
</div>
<div class="ctop_bottom">
<div class="bottom_title">相关电子档案</div>
<div ><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/word_small.gif"/><span><a href="">附件二：总裁发言稿</a></span><label>附件</label></div>
<div><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/word_small.gif"/><span><a href="">附件三：与会人员签到稿</a></span><label>附件</label></div>
<div><img alt="" src="<?php echo $tplPath?>/ESArchiveSeache/img/word_small.gif"/><span><a href="">中国联通工作会议纪要</a></span><label>附件</label></div>
</div>
</div>
<div class="clear"></div>
</div>

</div>
<script type="text/javascript">
$(document).ready(function(){
	
	$(".front_sck").mouseover(function(){
		$(this).css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/application.gif')"});
		$(".bot_content").css({display:"block"});
		});
	
	$(".bot_content").mouseover(function(){
		$(".front_sck").css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/or_bg.gif')"});
		$(this).css({display:"block"});
		$(".front_sck").css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/application.gif')"});
	});
		$(".bot_content").mouseout(function(){
		$(".front_sck").css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/or_bg.gif')"});
		$(this).css({display:"none"});
	});
	$(".cr2").mouseover(function(){
		//alert(111);
		$(this).css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/c2_hover.gif')"});
	});
	$(".cr2").mouseout(function(){
		//alert(111);
		$(this).css({background:"url('<?php echo $tplPath?>/ESArchiveSeache/img/c2_or.gif')"});
	});

});
</script>