<style type="text/css">
<!--
a img {border: 0 none;}
a{text-decoration:none;}

.main{position:relative;width:100%;min-width:980px;overflow:hidden;}
.main table td{font-size:13px;padding-right:15px;}
-->
</style>
<div class="main">
<table >
<tbody>
<tr>
<td><input id="province1" type="checkbox" /><label for="province1">联通总部</label></td>
<td><input id="province2" type="checkbox" /><label for="province2">北京分公司</label></td>
</tr>
<tr>
<td><input id="province3" type="checkbox" /><label for="province3">联通总部</label></td>
<td><input id="province4" type="checkbox" /><label for="province4">北京分公司</label></td>
</tr>
<tr>
<td><input id="province5" type="checkbox" /><label for="province5">联通总部</label></td>
<td><input id="province6" type="checkbox" /><label for="province6">北京分公司</label></td>
</tr>
<tr>
<td><input id="province7" type="checkbox" /><label for="province7">联通总部</label></td>
<td><input id="province8" type="checkbox" /><label for="province8">北京分公司</label></td>
</tr>
<tr>
<td><input id="province9" type="checkbox" /><label for="province9">联通总部</label></td>
<td><input id="province10" type="checkbox" /><label for="province10">北京分公司</label></td>
</tr>
<tr>
<td><input id="province11" type="checkbox" /><label for="province11">联通总部</label></td>
<td><input id="province12" type="checkbox" /><label for="province12">北京分公司</label></td>
</tr>
</tbody>
</table>
</div>