
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESAppClientConfig/css/main.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESAppClientConfig/js/template.js"></script>
<script type="text/javascript" src="/templates/es/js/jquery.form.js"></script>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app, 'title'=>'配置管理'));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>5));?>
<div id='ESAppClientConfig' class = "ESAppClientConfigContainer">
	<table id="config"></table>
</div>
