<div class='log-detail'>
	<div class='log-form'>
		<h2>登录日期</h2>
		<p id='loginDate'>...</p>
		<h2>登录时间</h2>
		<p class='clear' id='loginTime'>...</p>
		<i></i>
		<h2>登录用户</h2>
		<p id='userName'>...</p>
		<h2>IP 地址</h2>
		<p class='clear' id='IPaddress'>...</p>
		<i></i>
		<h2>用户部门</h2>
		<p class='long' id='orgName'>...</p>
		<i></i>
		<h2>操作功能</h2>
		<p class='long' id='operate'>...</p>
		<i></i>
		<h2 class='tall'>操作明细</h2>
		<div><textarea readonly='readonly' id='operateDetail'>...</textarea></div>
	</div>
</div>