<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESArchiveLending/css/orgtree.css" />
<div style="width:600px;height:500px;overflow-y:auto;overflow-x:hidden;position:relative;">
    <div>
      <form id="form_update" method="post" action="" enctype="multipart/form-data">
      <input type="hidden" name="submit" value="add"/>
      <input type="hidden" name="readerid" value="<?php echo $readerid;?>"/>
      <input type="hidden" name="deptcode" value="<?php echo $deptcode;?>"/>
      <div class="contentDiv">
      	<ul>
      		<li class="leftTv">借阅人&nbsp;<font color="red" size="3">*</font></li>
      		<li id="btnIn">
      			<input type="text" value="<?php echo $reader;?>" title="请输入外来借阅人" name="reader"/>
      			<span><img id="btn" title="单击我,可选择系统内借阅人信息" src="<?php echo $tplPath;?>/ESArchiveLending/images/group.png"/></span>
      		</li>
      		<li class="rightTv">单位</li>
      		<li id="dept">
      			<input type="text" value="<?php echo $dept;?>" name="dept"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">电话</li>
      		<li>
      			<input type="text" value="<?php echo $tel;?>" name="tel"/>
      		</li>
      		<li class="rightTv">邮箱</li>
      		<li>
      			<input type="text" value="<?php echo $email;?>" name="email"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">利用目的</li>
      		<li>
      			<select name="usepurpose" id="selectSty" style="width:184px;height:23px;line-height:23px;">
					<option value="编史修志">编史修志</option>
					<option value="工作查考">工作查考</option>
					<option value="学术研究">学术研究</option>
					<option value="经济建设">经济建设</option>
					<option value="宣传教育">宣传教育</option>
					<option value="其他">其他</option>
				</select>
      		</li>
      		<li class="rightTv">催还提前天数&nbsp;<font color="red" size="3">*</font></li>
      		<li>
      			<!-- <select name="select" id="select" style="clip:rect(0 184 22 162);"  onchange="validdate.value=select.options[select.selectedIndex].text;validdate.select()">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3" selected="selected">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
				</select> -->
				<input type="text" name="validdate" value="<?php echo $validdate;?>"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">登记人</li>
      		<li>
      			<input type="text" value="<?php echo $register;?>" name="register" readonly="readonly"/>
      		</li>
      		<li class="rightTv">登记日期</li>
      		<li>
      			<input type="text" id='times' readonly='readonly' value="<?php echo $registdate;?>" name="registdate"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">状态</li>
      		<li>
      			<input type="text" value="<?php echo $status;?>" id="status" readonly="readonly" name="status"/>
      		</li>
      	</ul>
      	<ul>
      		<li class="leftTv">备注</li>
      		<li>
      			<textarea style="resize:none;text-indent:2px;width:487px;height:50px;font-size:12px;font-family:Arial, Helvetica, sans-serif, 宋体" name="description"><?php echo $description;?></textarea>
      		</li>
      	</ul>
      </div>
      </form>
	  <div class="bottom" >
		<table id="borrowDetails"></table>
	  </div>
	</div>
<script type="text/javascript">
$(function(){
	arType="<?php echo $arType;?>";
	formReaderId="<?php echo $readerid;?>";
	if(formReaderId){
		IreaderD=1;
	}else if(formReaderId==''){
		IreaderD=0;
	}
	var value=["<?php echo $usepurpose;?>"];
	$("[value="+value+"]").attr('selected',true);
	$("input[name='tel']").keyup(function(){
		var regTel=/^((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})$))$/g;
		if((!regTel.test(this.value))&&(this.value!='')){
			$("input[name='tel']").addClass("invalid-text").attr("title","请输入合法的电话号码");
			return false;
		}
		$(this).removeClass("invalid-text").attr("title","");
	});
	$("input[name='email']").keyup(function(){
		var regEmail=/^[\w]+([-.][\w]+)*@[\w]+([-.]\w+)*\.[\w]+(\.[\w]+)?$/;
		if((!regEmail.test(this.value))&&(this.value!='')){
			$("input[name='email']").addClass("invalid-text").attr("title","请输入合法的邮箱");
			return false;
		}
		$(this).removeClass("invalid-text").attr("title","");
	});
	$("input[name='validdate']").keyup(function(){
		var reg=/^[1-9]\d*$/;
		if(!reg.test(this.value)){
			$("input[name='validdate']").addClass("invalid-text").attr("title","此项不能为空且只能输入大于零的数字");
		    return false;
		}
		if(this.value > 30){
			$("input[name='validdate']").addClass("invalid-text").attr("title","借出天数不能超过30天");
		    return false;
		}
		$(this).removeClass("invalid-text").attr("title","");
	});
	/*$("select[name='select']").change(function(){
		$("input[name='validdate']").removeClass("invalid-text").attr("title","");
	});*/
	//单位点击事件触发focus/click
	var foo=function(){
		var stut=$("input[id='status']").val();
		if(stut!='未提交' && stut!='已退回'){
			$.dialog.notice({content:'提交审批中或借阅中,不允许更改！',icon:'warning',time:3});
			return false;
		}else{
			var content = [];
			content.push("<table>");
			content.push("<tr>");
			content.push("<td>");
			content.push("<div id='orgtreebox' style='width:200px; height:350px;overflow:auto;'><ul id='orgtree' class='ztree'></ul></div>");
			content.push("</td>");
			content.push("<td>");
			content.push("<div id='personlistbox' style='height:350px;overflow:auto;'>");
			content.push("<table id='personlist'></table>");
			content.push("</div>");
			content.push("</td>");
			content.push("</tr>");
			content.push("</table>");
			$.dialog({
				title:'选择单位和借阅人',
	    		width: '700px',
	    	   	height: '350px',
	    	   	padding: '0px',
	    	    fixed:true,
	    	    resize: false,
	    		content:content.join(""),
	    		cancelVal: '取消',
	    		cancel: true,
	    		okVal: '保存',
	    		ok: function(){
		    		// 填入单位和借阅人信息
		    		var radioId = $("#personlist").find("input:checked").attr('id');
					if(radioId=='' || radioId==undefined){
						$.dialog.notice({title:'操作提示',icon:'warning',content:'请选择单位下的借阅人！'});
						return false;
					}
					var listId=radioId.split('|');
					$("input[name='readerid']").val(listId[0]);
					$("input[name='deptcode']").val(listId[1]);
					var radioName = $("#personlist").find("input:checked").attr('value');
					var list=radioName.split('|');
					$("input[name='reader']").val(list[0]);
					$("#dept input[name='dept']").val(list[1]);
					$("input[name='tel']").val(list[2]);
					$("input[name='email']").val(list[3]);
		    		
		    		this.close();
		    		IreaderD=1;
		    		$("input[name='reader']").removeClass("invalid-text").attr({"title":""});
		    		return false;
		    	},
				init:initSelectOrg
	    	});
			// 初始化选择单位和借阅人界面
			function initSelectOrg(){
				createOrgTree();
				createPersonList();
			}
		}
	};
	$("#btnIn img").bind("click",foo);
	$("input[name='reader']").keydown(function(){
		var stut=$("input[id='status']").val();
		if(stut!='未提交' && stut!='已退回'){
			$.dialog.notice({content:'提交审批中或借阅中,不允许更改！',icon:'warning',time:3});
			return false;
		}
	});
	$("input[name='reader']").keyup(function(){
		$("#dept input[name='dept']").val("");
		$("input[name='tel']").val("");
		$("input[name='email']").val("");
		$(this).removeClass("invalid-text").attr("title","您输入的借阅人为外来人员");
		IreaderD=0;
	});
	// 创建机构树目录
	function createOrgTree(){
		var setting = {
				view: {
					dblClickExpand: false,
					showLine: false
				},
				data: {
					simpleData: {
						enable: true
					}
				},
				async: {
					enable: true,
					dataType: 'json',
					url: $.appClient.generateUrl({ESArchiveLending:'getSubOrgList'},'x'),
					autoParam: ["id"]
				},
				callback: {
					onClick : nodeClick
				}
			};
			function nodeClick(event, treeId, treeNode){
				zTree = $.fn.zTree.getZTreeObj("orgtree");
				zTree.expandNode(treeNode);
				$("#personlist").flexOptions({url:$.appClient.generateUrl({ESArchiveLending:'getPersonList',orgid:treeNode.id},'x')}).flexReload();	
			};
			var url = $.appClient.generateUrl({ESArchiveLending:'initOrg'},'x');
			$.ajax({
				url:url,
				dataType: 'json',
				success:function(nodes){
					$.fn.zTree.init($("#orgtree"), setting, nodes);
				},
				cache:false
			});
	};
	// 显示人员列表
	function createPersonList(){
		$("#personlist").flexigrid({
			url:false,
			dataType: 'json',
			editable: true,
			colModel : [
				{display: '操作', name : 'id2', width : 40, align: 'center'},
				{display: '姓名', name: 'c1',  width : 68, align: 'center'},
				{display: '联系电话', name: 'c2',width:110,align:'center'},
				{display: '邮箱', name: 'c3',width:120,align:'center'},
				{display: '所属机构', name: 'c4', width:100,align:'center'}
			],
			usepager: true,
			rp: 50,
			useRp: true,
			width: 500,
			height: 290
		});
	}
	//借阅明细全选按钮
	$("input[name='ids3']").die().live('click',
		function(){
			$("input[name='id3']").attr('checked',$(this).is(':checked'));
		}
	);
});
</script>
</div>