<div class="content940">
  <div class="Operations_contop">
  <table align="center" class=" OperNameTable">
  <tr>
    <td><a href="#search" name="top"><img src="<?php echo $tplPath ?>/images/icons/search_icon1.gif" width="30" height="32" style="vertical-align:middle" /> 统一搜索</a></td>
    <td><a href="#setting"><img src="<?php echo $tplPath ?>/images/icons/setting.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 个人设置</a></td>
    <td><a href="#undo_todo"><img src="<?php echo $tplPath ?>/images/icons/undo_todo.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 待办待阅</a></td>
    <td><a href="#app_center"><img src="<?php echo $tplPath ?>/images/icons/app_center.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 应用订购与审批</a></td>
  </tr>
  <tr>
    <td><a href="#weather"><img src="<?php echo $tplPath ?>/images/icons/weather.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 天气预报</a></td>
    <td><a href="#stocks"><img src="<?php echo $tplPath ?>/images/icons/stocks.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 股票</a></td>
    <td><a href="#bbs"><img src="<?php echo $tplPath ?>/images/icons/bbs.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 论坛</a></td>
    <td><a href="#weibo"><img src="<?php echo $tplPath ?>/images/icons/weibo.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 微博</a></td>
  </tr>
  <tr>
    <td><a href="#albums"><img src="<?php echo $tplPath ?>/images/icons/albums.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 相册</a></td>
    <td><a href="#perinfo"><img src="<?php echo $tplPath ?>/images/icons/perinfo.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 个人资料汇聚</a></td>
    <td><a href="#goodfriends"><img src="<?php echo $tplPath ?>/images/icons/goodfriends.gif" alt="" width="32" height="32" style="vertical-align:middle" /> 好友动态</a></td>
    <td><a href=""></a></td>
  </tr>
</table>
  </div>
  <div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="search" style="vertical-align:middle">统一搜索</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 统一搜索</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 同事搜索</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 搜索框</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 应用搜索</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 信息搜索</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 加同事好友</a></td>
      </tr>
    </table>
  <div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="setting">个人设置</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td width="135"><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 布局设置</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 栏目设置</a></td>
      </tr>
    </table>
  <div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="undo_todo">待办待阅</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 待办待阅提醒设置</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 代办委托设置</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 代办业务查询</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 进入待办待阅的方式</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 领导待办催办设置</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 已阅业务列表展示</a></td>
      </tr>
    </table>
    <div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="app_center">应用订购与审批</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 订购一个APP去java控制台</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 订购一个app去PHP界面</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 批量订购app去java控制台</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 批量订购app去PHP界面</a></td>
      </tr>
    </table>
<div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="weather">天气预报</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td width="135"><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 天气预报设置</a></td>
        <td>&nbsp;</td>
      </tr>
    </table>
    <div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="stocks">股票</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td width="135"><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 股票设置</a></td>
        <td>&nbsp;</td>
      </tr>
    </table>
    <div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="bbs">论坛</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 创建群组</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 加入群组</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 退出群组</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除群组员</a></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 发布新帖子</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 编辑帖子</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除帖子</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 回复帖子</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除帖子回复</a></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 帖子列表加精华</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 帖子列表锁帖</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 帖子列表取消精华</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 帖子列表解锁</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 帖子置顶</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 取消置顶</a></td>
      </tr>
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 管理员加精华</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 管理员锁帖</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 管理员取消精华</a></td>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 管理员解锁</a></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table>
<div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="weibo">微博</a></div>
<table align="center" class=" OperListTable">
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览我的信息</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览他人信息</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览我的微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览他人微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 加关注</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 设置备注</a></td>
    </tr>
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 查看我的粉丝</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 发布新微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 转发微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 收藏微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 取消收藏微博</a></td>
    </tr>
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 回复微博</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 对回复进行回复</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除我的回复</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 查看我的回复列表</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 查看我的私信</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 发送新私信</a></td>
    </tr>
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 回复发给我的私信</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除发给我的私信</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 举报</a></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
<div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="albums">相册</a></div>
<table align="center" class=" OperListTable">
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览我的相册列表</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览他人的相册列表</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览我的图片详细页</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览他人图片详细页</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 添加相册</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除相册</a></td>
  </tr>
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 相册更名</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 旋转图片</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 缩放图片</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除图片</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 单个图片上传</a></td>
    <td>&nbsp;</td>
  </tr>
</table>
<div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="perinfo">个人资料汇聚</a></div>
<table align="center" class=" OperListTable">
  <tr>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 浏览个人信息</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 新增工作经历</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除工作经历</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 新增紧急联系人</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 删除紧急联系人</a></td>
    <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 修改教育经历</a></td>
  </tr>
</table>
<div class="Operations_title"><span class="floatRight"><a href="#top">to top</a></span><a  name="goodfriends">好友动态</a></div>
    <table align="center" class=" OperListTable">
      <tr>
        <td><a href=""><img src="<?php echo $tplPath ?>/images/video.gif" alt="" width="16" height="16" style="vertical-align:middle" /> 查看我的空间好友动态</a></td>
        <td>&nbsp;</td>
      </tr>
    </table>
</div>
<?php echo $this->render('footer.phtml') ?>
