<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link href="<?php echo $tplPath?>/ESFormManage/css/style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php echo $tplPath;?>/public/ztree/css/zTreeStyle/zTreeStyle.css" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js"></script>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app, 'title'=>'流程监控'));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>5));?>
<!-- 左侧 -->
<div id="leftdiv" class="leftdiv" style="float:left;width:180px;margin-left:5px;">
  <div style="background-color: #ECECEC;height:22px;margin-top:5px;">
  <img src="<?php echo $tplPath?>/ESTemplate/img/chakan.jpg" /><span>流程监控树</span>
</div>	
  <input type="submit" onclick=""  value="添加" />
    <input type="button" onclick="" value="编辑" />
  <input type="button" onclick="" value="删除" />
  <div style="clear:both;"></div>
  <ul id="treeDemo" class="ztree" style="margin-top:-30px;"></ul>	
</div>

<!-- 右侧 -->
<div id="rightdiv" ><table id="flexme1">
</table>
<script type="text/javascript">
    var uri="<?php echo url($this->getUrl($esaction->generateUrl(Array('ESFlowMonitor'=>'set_json'))));?>";</script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFlowMonitor/js/template.js"></script>

</div>

