<!-- yanghuiqiang 20140522 消息详细窗口-->

<style>
<!--
#addReport table tr {
	height: 50px;
}
-->
</style>
<style type="text/css">
.mydiv p {
	margin: 0px;
	padding: 0px;
}
</style>
<div style="">
	<div style="padding-top: 30px;">
		<form id="detail" method="post" enctype="multipart/form-data">
			<table id="table_detail" style="height: 200px;">
				<tr>
					<td><input type="hidden" name="id" id="id"
						value="<?php echo $message->id;?>"
						style="width: 380px; height: 0px;" /></td>
				</tr>
				<tr>
					<td>消息类型：</td>
					<td><input type="text" name="type" id="type"
						value="<?php echo $message->pushType;?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>
				<tr>
					<td>发送方：</td>
					<td><input type="text" name="sender" id="sender"
						value="<?php echo $message->sender == -1 ? "系统":$message->sender;?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>
				<tr>
					<td>接收方：</td>
					<td><input type="text" name="receiver" id="receiver"
						value="<?php echo $message->receiver;?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>

				<tr>
					<td>消息内容：</td>
					<td><div class="mydiv" id="msgDiv"
							style="background-color: #eeeeee; border-left-style: inset; border-top-style: inset; border: 1; width: 380px; height: 100px; cursor: text">
							<?php echo $message->content;?>
						</div></td>
				</tr>
				
				<tr>
					<td>处理方式：</td>
					<td><input type="text" name="messageHanderType" id="messageHanderType"
						value="<?php echo $message->messageHanderType;?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>
				
				<tr>
					<td>附加内容：</td>
						<td><textarea name="data" id="data"
							style="width: 380px; height: 100px;"><?php echo $message->data;?></textarea></td>
				</tr>

				<tr>
					<td>发送时间：</td>
					<td><input type="text" name="time" id="time"
						value="<?php echo gmdate("Y-m-d H:i:s", ($message->timeStamp / 1000) + 8*3600);?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>

			</table>
		</form>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$('#table_detail input:text').attr("readOnly", true); 
	$('#table_detail textarea').attr("readOnly", true);
});
</script>

