
<style type="text/css">
.fieldset_taskschedul {
	border: 1px solid #ccc;
	padding: 10px;
	width: 410px;
	margin: 0px;
}

.legend_taskshedul {
	font-size: 12px;
	border-bottom: 0px;
	margin-bottom: 0px;
	width: auto;
	font-weight: bold;
}

.label_taskshedul {
	margin: 8px;
	margin-top: 0px;
}

.text_taskschedul {
	width: 200px;
	margin-left: 10px;
	padding: 3px;
	required: true;
}

.select_taskshedul {
	width: 208px;
	margin-left: 10px;
	padding: 3px;
}

.form_taskshedul {
	
}

.radio_taskshedul {
	margin: 0 5px 0 20px;
}

.radio_selectNumber {
	margin: 0 5px 0 20px;
}
</style>
<form id="jobForm">
	<fieldset class="fieldset_taskschedul">
		<legend class="legend_taskshedul">请输入任务调度信息：</legend>
		<p>
			<label class="label_taskshedul">任务名称：<input type="text"
				name="jobName" class="text_taskschedul" />
			</label>
		</p>
		<p>
			<label class="label_taskshedul">任务类名：<select
				class="select_taskshedul" name="jobClass">
					<option value="TestJob">日志备份删除</option>
					<option value="TestJob">批量转换缩略图</option>
					<option value="TestJob">机构用户同步</option>
					<option value="TestJob">索引库自动维护</option>
					<option value="TestJob">介质预警</option>
			</select>
			</label>
		</p>
		<p>
			<label class="label_taskshedul">任务描述：<input type="text"
				class="text_taskschedul" name="description" />
			</label>
		</p>
	</fieldset>

	<fieldset class="fieldset_taskschedul">
		<legend class="legend_taskshedul">请选择频率(*请选择一种发生方式)：</legend>
		<p>
			<label class="label_taskshedul">设置频率：<input name="seleteNumber"
				type="radio" value="1" class="radio_selectNumber" />每天 <input
				name="seleteNumber" type="radio" value="2"
				class="radio_selectNumber" />每周 <input name="seleteNumber"
				type="radio" value="3" checked="checked" class="radio_selectNumber" />每月
			</label>
		</p>
		<p>
			<label class="label_taskshedul">精确时间： <input type="text"
				id="ererydaytime" class="Wdate" name="ererydaytime"
				onClick="WdatePicker({dateFmt:'H:mm:ss'})" value="00:00:00" />
			</label>
		</p>
		<p>
			<label class="label_taskshedul" id="everyMothLabel">每&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;月：
				<input type="text" id="ererymonth" class="Wdate" name="ererymonth"
				onClick="WdatePicker({dateFmt:'dd'})" value="01" />
			</label>
		</p>
		<p>
			<label class="label_taskshedul" style="visibility: hidden"
				id="everyWeekLabel">每&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;周：<select
				class="select_taskshedul" name="ereryweek"
				style="visibility: hidden" id="everyWeekOption">
					<option value="1">星期一</option>
					<option value="2">星期二</option>
					<option value="3">星期三</option>
					<option value="4">星期四</option>
					<option value="5">星期五</option>
					<option value="6">星期六</option>
					<option value="7">星期天</option>
			</select>
			</label>
		</p>
		<p>
			<label class="label_taskshedul" style="visibility: hidden"
				id="everyWeekGeLabel">每隔几周： <input name="weekday"
				class="text_taskschedul"
				onkeyup="this.value=this.value.replace(/\D/g,'')" value="2"
				onafterpaste="this.value=this.value.replace(/\D/g,'')" maxlength="5"
				size="14" name="amount" style="visibility: hidden"
				id="everyWeekGeDate" />
			</label>
		</p>
	</fieldset>

	<fieldset class="fieldset_taskschedul">
		<legend class="legend_taskshedul">请选择年份范围：</legend>
		<p>
			<label class="label_taskshedul">设置结束：<input name="isHasEndtime"
				type="radio" value="1" class="radio_taskshedul" checked="checked" />否
				<input name="isHasEndtime" type="radio" value="2"
				class="radio_taskshedul" />是

			</label>
		</p>
		<p>
			<label class="label_taskshedul" id = "startYearlabel">开始年份： <input type="text" class="Wdate"
				name="start" onClick="WdatePicker({dateFmt:'yyyy'})" />
			</label>
		</p>
		<p>
			<label class="label_taskshedul" id="endYearlabel"
				style="visibility: hidden">结束年份： <input type="text" class="Wdate"
				name="end" onClick="WdatePicker({dateFmt:'yyyy'})" />

			</label>
		</p>
	</fieldset>
</form>
<script>
/* 年份范围事件 */
$(".radio_taskshedul").change(function() {
	var $selectedvalue = $("input[name='isHasEndtime']:checked").val();
	if($selectedvalue == 2){
		$("#endYearlabel").css("visibility","");
		$("#endYearDate").css("visibility","");
	}else{
		$("#endYearlabel").css("visibility","hidden");
		$("#endYearDate").css("visibility","hidden");
	}
});

/** 频率事件**/
$(".radio_selectNumber").change(function() {
	var $selectedvalue = $("input[name='seleteNumber']:checked").val();
	if($selectedvalue == 1){
		$("#everyMothLabel").css("visibility","hidden");
		$("#everyMothDate").css("visibility","hidden");
		$("#everyWeekLabel").css("visibility","hidden");
		$("#everyWeekOption").css("visibility","hidden");
		$("#everyWeekGeLabel").css("visibility","hidden");
		$("#everyWeekGeDate").css("visibility","hidden");
	}else if($selectedvalue == 2){
		$("#everyMothLabel").css("visibility","hidden");
		$("#everyMothDate").css("visibility","hidden");
		
		$("#everyWeekLabel").css("visibility","");
		$("#everyWeekOption").css("visibility","");
		$("#everyWeekLabel").css("margin-top","-25px");
		
		$("#everyWeekGeLabel").css("visibility","");
		$("#everyWeekGeDate").css("visibility","");
	}else{
		$("#everyMothLabel").css("visibility","");
		$("#everyMothDate").css("visibility","");
		$("#everyWeekLabel").css("visibility","hidden");
		$("#everyWeekOption").css("visibility","hidden");
		$("#everyWeekGeLabel").css("visibility","hidden");
		$("#everyWeekGeDate").css("visibility","hidden");
	}
});
</script>

