<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/autovalidate/style.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/autovalidate/validate.js"></script>
<div id="viewOnlineUserDiv">
	<form id="viewOnlineUserForm" method="post" enctype="multipart/form-data">
<table style="height:100px;">
  <tr>
    <td>企业名称:</td>
    <td><input type="text" name="title" verify="text/5/1/0" id="title" style="width:380px;height:20px;"  /></td>
  </tr>
  <tr>
    <td>企业地址:</td>
    <td><input type="text" name="title" verify="text/5/1/0" id="title" style="width:380px;height:20px;"  /></td>
  </tr>
  <tr>
    <td>企业主页地址:</td>
    <td><input type="text" name="title" verify="text/5/1/0" id="title" style="width:380px;height:20px;"  /></td>
  </tr>
  <tr>
    <td>激活邮箱地址:</td>
    <td><input type="text" name="title" verify="text/100/1/0" id="title" style="width:380px;height:20px;"  /></td>
  </tr>
  <tr>
    <td>管理员名称:</td>
     <td>
     <input type="text" name="title" verify="text/100/1/0" id="title" style="width:380px;height:20px;"  />
    </td>
  </tr>
  <tr>
    <td>手机:</td>
    <td><input type="text" name="title" verify="text/5/1/0" id="title" style="width:380px;height:20px;"  /></td>
  </tr>
  <tr>
    <td>传真:</td>
    <td><input type="text" name="title" verify="text/5/1/0" id="title" style="width:380px;height:20px;"  /></td>
  </tr>
  
</table>
</form>

</div>


