<div id="batchmodify">
<div id='addrolefree'>
	<h2 class='h2'>批量修改设置</h2>
	<p class='contbox'>
		<span class='w140 w14090 hei30'>字段名</span>
		<span class='w90 w14090 hei30'>比较符</span>
		<span class='w140 w14090 hei30'>字段值</span>
		<span class='w90 w14090 hei30'>关系符</span>
	</p>
	<div id='contents'>
		<!-- 1 -->
		<p class='contbox creatediv'>
			<select class='w140 w14090 hei20 filedname'>
				<option value=''>--请选择--</option>
				<option value='CODE'>库房编号</option>
				<option value='ARCHIVE_CODE'>档号</option>
				<option value='TITLE'>题名</option>
				<option value='TYPE'>类型</option>
				<option value='STATUS'>状态</option>
				<option value='REASON'>出入库原因</option>
				<option value='MANAGER'>办理人</option>
				<option value='DATE'>办理日期</option>
			</select>
			<select class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like">包含</option>
				<option value="notLike">不包含</option>
			</select>
			<input type='text' class='w140 w14090 hei20 filedvalue' />
			<select id='' class='w14090 w90 hei20 relationship'>
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select>
			<a class='newfilter'>添加行</a> 
			<a class='delfilter'>删除行</a>
		</p>
				<p class='contbox creatediv'>
			<select class='w140 w14090 hei20 filedname'>
				<option value=''>--请选择--</option>
				<option value='CODE'>库房编号</option>
				<option value='ARCHIVE_CODE'>档号</option>
				<option value='TITLE'>题名</option>
				<option value='TYPE'>类型</option>
				<option value='STATUS'>状态</option>
				<option value='REASON'>出入库原因</option>
				<option value='MANAGER'>办理人</option>
				<option value='DATE'>办理日期</option>
			</select>
			<select class='w90 w14090 hei20 comparison'>
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like">包含</option>
				<option value="notLike">不包含</option>
			</select>
			<input type='text' class='w140 w14090 hei20 filedvalue' />
			<select id='' class='w14090 w90 hei20 relationship'>
				<option value="AND" selected="selected">并且</option>
				<option value="OR">或者</option>
			</select>
			<a class='newfilter'>添加行</a> 
			<a class='delfilter'>删除行</a>
		</p>
				 
	</div>
</div>
<hr width="100%" />
<div class="changestate">
<form id="batchform">

<div class="sst"><span class="bas1">状态</span><select class="bas2" name="status" class="status"><option>入库</option><option>借出</option><option>销毁</option><option>移出</option><option>缺失</option></select></div>

<div class="sst sst1"><span class="bas1 bas3">出入库原因</span><textarea  class="bas2 edit0" name="reason" id="reason" ></textarea></div>



</form>
</div>
</div>
<script type="text/javascript">
$('.newfilter').die().live('click',function (){
	$(this).parent().clone().insertAfter($(this).parent());
});

$('.delfilter').die().live('click',function (){
	$('#contents p').length > 1 ? $(this).parent().remove() : '';
});
</script>