<style>
<!--
#statechange{z-index:99999;}
-->
</style>
<div>
<table id="statechange"></table>
</div>
<script type="text/javascript">
$(function(){

	$("#statechange").flexigrid({
		dataType: 'json',
		editable:true,
		colModel : [
			{display: '库房编号', name : 'num', width : 80, align: 'center'}, 
			{display: '档号', name : 'c3', width : 100, sortable : true, align: 'center'},
			{display: '题名', name : 'c4', width : 100, sortable : true, align: 'center'},
			{display: '状态', name : 'c6', width : 80, sortable : true, align: 'center',editable:true,dropdown:["入库", "借出","销毁","移出","缺失"]},
			{display: '出入库原因', name : 'c7', width : 180, sortable : true, align: 'center',editable:true}
			],
		sortname: "c3",
		sortorder: "asc",
		usepager: true,
		useRp: true,
		rp: 20,
		nomsg:"没有数据",
		showTableToggleBtn: false,
		pagetext: '第',
		outof: '页 /共',
		width: 600,
		height: 300,
		pagestat:' 显示 {from} 到 {to}条 / 共{total} 条'
	});
	$("#statechange").flexOptions({newp:1,url:mychangeurl,query:id}).flexReload();
	
});

</script>