<!-- caojian 20140423-->
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link href="<?php echo $tplPath?>/ESOrder/css/reply.css" rel="stylesheet" type="text/css">
<script	type="text/javascript" src="<?php echo $tplPath;?>/public/js/jquery.appclient.setting.js?baseurl=<?php echo $esaction->generateUrl(array());?>"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESOrder/js/reply.js"></script>
<div id='replyList' class='init-style'>
	<input type="hidden" id="orderid" value=<?php echo $orderid ?> />
	<table id="replyListGrid" class="reply">
	</table>
</div>
