<div class="espakcet">
<ul>
<li><span>盒号</span><input type="text" name="" value=""></li>
<li><span>盒厚度</span><input type="text" name="" value=""></li>
<li><span>盒容量</span><input type="text" name="" value=""></li>
<li><span>档案类型</span><input type="text" name="" value=""></li>
<li><span>保管期限</span><input type="text" name="" value=""></li>
<li><span>年度</span><input type="text" name="" value=""></li>
<li style="width:420px"><span>盒名称</span><input type="text" name="" value="" style="width:350px"></li>
<li style="width:420px"><span>备注</span><textarea style="width:350px;height:50px;float:left"></textarea></li>
</ul>
</div>