<div class='esmain'>
	<div class="esleft">
	
	</div>
	<div class="esright">
		<div class="esfile">
			<div class="esfilehead">
				<span  class="estitle">关于董事长和王总裁在2004年中国联通工作会上讲话通知</span>
				<table align="center">
				<tr>
				<td>文号：中国联通综字[2004]195号 </td>
				<td>题名:关于董事长和王总裁在2004年中国联通工作会上讲话通知 </td>
				<td>责任者:中国联通集团公司</td>
				</tr>
				<tr>
				<td>保管期限:长期  </td>
				<td>密级:公开</td>
				<td>日期:2004-5-24</td>
				</tr>
				<tr>
				<td>页数:16</td>
				<td>年度:2004</td>
				<td>备注: 件号:0152</td>
				</tr>
				<tr>
				<td>所属部门:综合部</td>
				<td>标识: 2 </td>
				<td>全宗号:001</td>
				</tr>
				</table>
				<div class="esnav">
				<a href="#"><span class="attachments"><span style="margin-left:30px;">附件一:董事长发言稿</span></span></a>
				<a href="#"><span class="esdown"><span style="margin-left:10px;">下载此电子档案</span></span></a>
				<a href="#"><span class="esapply"><span>申请档案权限</span></span></a>
				</div>
			</div>
			<div class="esfileview">
				文件浏览区域
			</div>
		</div>
		<div class="esfileinfo">
			<span>电子文档信息</span>
			<hr width="90%">
			<ul>
				<li>浏览次数</li>
				<li>下载次数</li>
				<li>文件类型</li>
				<li>文件格式</li>
				<li>创建者</li>
				<li>创建时间</li>
				<li>文件大小</li>
			
			</ul>
			<span>相关电子文档</span>
			<hr width="90%">
			<ul>
				<li><a href="">附件二:总裁发言稿</a></li>
				<li><a href="">附件二:总裁发言稿</a></li>
				<li><a href="">附件二:总裁发言稿</a></li>
				<li><a href="">附件二:总裁发言稿</a></li>
				<li><a href="">附件二:总裁发言稿</a></li>
			</ul>
		</div>
	</div>
</div>