<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="<?php echo $tplPath;?>/public/ztree/css/zTreeStyle/zTreeStyle.css" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESFileEquipment/css/style.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFileEquipment/js/setNetSegment.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/autovalidate/style.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/autovalidate/validate.js"></script>

<div id="ESLoginNetSegment" class = "netSegmentContainer" priority = "<?php echo $priority;?>" fileStoreId = "<?php echo $fileStoreId;?>">
  <table id="loginNetSegment"></table>
</div>