<!-- yanghuiqiang 20140522 检索关键字管理-->
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="<?php echo $tplPath;?>/public/ztree/css/zTreeStyle/zTreeStyle.css" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESAppClientSearchKeyword/css/main.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESAppClientSearchKeyword/js/template.js"></script>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app, 'title'=>'档案检索关键字信息列表'));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>5));?>

<div id='ESAppClientSearchKeyword' class = "ESAppClientSearchKeywordContainer">
	<div class='leftDiv' id='leftDiv'>
		<div id='type_all'>
			<a href='javascript:;' class='selected' id='all'>全部</a>
			<a href='javascript:;' id='order'>关键字统计</a>
		</div>
	</div>
	<div class='rightDiv' id='rightDiv'> 
		 <table id="searchKeyword"></table>
	</div>
</div>