<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/autovalidate/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/ESUserStatus/css/style.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/autovalidate/validate.js"></script>
<div id="user_menu">
				<div id="current_user_avatar"></div>
				<span id="current_user_name" class="overflow_ellipsis">guolanrui</span>
				<img id="connection_icon" src="" class="" style="">
				<span id="connection_status">online</span>
</div>

