<meta http-equiv="content-type" content="text/html; charset=utf-8">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/DatePicker/WdatePicker.js"></script>
  <link href="<?php echo $tplPath?>/ESUserRegistration/css/style.css" rel="stylesheet" type="text/css">
  <link href="<?php echo $tplPath?>/ESUserRegistration/js/autovalidate/style.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="<?php echo $tplPath ?>/public/ztree/css/zTreeStyle/zTreeStyle.css" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>2));?>
 <script type="text/javascript" src="<?php echo $tplPath;?>/ESUserRegistration/js/common.js"></script>
 <script type="text/javascript" src="<?php echo $tplPath;?>/ESUserRegistration/js/autovalidate/validate.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/highcharts/js/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/highcharts/js/modules/exporting.js"></script>
<script>
$(document).ready(function(){
	$("#estabs").esTabs("open", {title:"用户注册", content:"#esmenu,#esone,#eslist"});
	function sizeChanged(){
		if($.browser.msie && $.browser.version==='6.0'){
			$("html").css({overflow:"hidden"});
		}
		var h = $(window).height() - $("#ESUserRegistration").position().top;
		var flex = $("#ESUserRegistrationGrid").closest("div.flexigrid");
		var bDiv = flex.find('.bDiv');
	    var contentHeight = bDiv.height();
	    var headflootHeight = flex.height() - contentHeight; 
	    bDiv.height(h - headflootHeight);
	    flex.height(h);
		// 修改IE表格宽度兼容
		if($.browser.msie && $.browser.version==='6.0'){
			flex.css({width:"-=3px"});
		}
	};
	//sizeChanged();
	$('div[class="tDiv2"]').append('<div class="find-dialog"><input id="userQuery" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="userQuery" value="请输入关键字" /><span id="userQueryButton"></span></div>');

	$(document).keydown(function(event){
		if(event.keyCode == 13 && document.activeElement.id == 'userQuery') {
			userQuery();
		}
	});

	$('#userQueryButton').click(function(){
		userQuery();
	});
	function userQuery(){
		var keyword = $.trim($('#userQuery').val());
		if(keyword == '' || keyword=='请输入关键字') {
			keyword = '';
		}
		$("#ESUserRegistrationGrid").flexOptions({query:keyword}).flexReload();
		return false;
	}
});
</script>
<div id='ESUserRegistration'  style="border:none;width:96%;margin-left:2%;">
        <table id="ESUserRegistrationGrid" style="border:none"></table>  
</div>

