<div style="height:auto;overflow-y:auto;overflow-x:0;width:auto">
<form id="escombination" >
<?php 
	if($flag==true){
?>


<table style="width:600px;margin-bottom:10px" id="sift">

	<tr>
		<td>字段名</td>
		<td>比较符</td>
		<td>字段值</td>
		<td>关系符</td>
		<td>增加行</td>
		<td>删除行</td>
	</tr>
	<?php for($i=0;$i<5;$i++){?>
	<tr>
		<td> <select name="esfields" style="width: 120px;">
				<option value="">--请选择--</option>
		<?php 
		foreach($searchField as $key=>$val){
				echo "<option value=".$val->name.">$val->display</option>";
}?></select></td>
		<td> <select name="comparison"  style="width: 70px;">
				<option value="equal">等于</option>
				<option value="greaterThan">大于</option>
				<option value="lessThan">小于</option>
				<option value="notEqual">不等于</option>
				<option value="greaterEqual">大于等于</option>
				<option value="lessEqual">小于等于</option>
				<option value="like" selected>包含</option>
				<option value="notLike">不包含</option>
			</select></td>
		<td><input type="text" value="" name="esfieldvalue" ></td>
		<td><select name="relation"  style="width: 60px;">
				<option value="AND">并且</option>
				<option value="OR">或者</option>
				</select></td>
		<td align="center"><a href="javascript:void(0)" class ="esadd"><div class="es_add"></div></a></td>
		<td align="center"><a href="javascript:void(0)" class ="esreduce"><div class="es_del"></div></a></td>
	</tr>
	
	<?php }?>
	
	
</table>
<?php }?>
<table style="width:600px;margin-top: 0px">
<tr>
<td><div class="tabs"  align="left">组合字段选择</div></td>
</tr>
<tr>
<td><hr width="100%" style="margin: 0 0 10px 0;"></td>
</tr>
<tr>
<td align="center">
<span class="tabs" >待组合字段<em style="color: red;">*</em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>

<select id="batchCombinationFieldName" name="batchCombinationFieldName" >
		<option value="">--请选择--</option>
		<?php 
		foreach($combinationFilelds->right as $key=>$val){
				echo "<option value=".$val->name.">$val->display</option>";
		}?>
</select>
</td>
</tr>
</table>
</form>
</div>
<div class="escatagory" id='catagory'>
<ul id="fication" class="ztree"></ul>
</div>
<div id="deadline">
<ul>
<?php foreach ($rpValLst as $value) {
    echo "<li>".$value."</li>";
}
?>
</ul>
</div>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESIdentify/js/catagory.js"></script>
<script type="text/javascript">
	var jsonData=<?php echo $string;?>;
	var index;//用于判断将分类号显示在第几个输入框
	$('[name="esfields"]').die().live('change',function(){
			var val=$(this).val();
			var t=$('[value='+val+']',$(this)).html();
			if(t!="保管期限"){
				$('#deadline').hide();
			}
			var obj=$(this).parents().next().next().children(':input');
			index=$(this).closest('tr').index();
			obj.attr('readonly',false);
			obj.unbind('click');
			obj.attr('verify',jsonData[val]);
			//如果是时间格式，修改为数字类型的验证
		/*	if(jsonData[val].search(reg)!=-1){
				var reg=/date/g;
				obj.attr('verify',jsonData[val].replace(reg,'number'));
			}*/
			//如果是分类号，需要见分类树显示
			if(t=="分类号"){
				obj.click(function(){
				var offset=obj.offset();
				$('#catagory').show().offset({top:offset.top+20,left:offset.left});
				
				});
			}
			if(t=="保管期限"){
				/*var s=  '<div style="width:137px;height:20px;"><select name="esfieldvalue" style="width:137px;height:20px;" id="select" style="clip:rect(0 184 22 162);" onchange="validdate.value=select.options[select.selectedIndex].text;">';
					s+=	'<option value = "永久">永久</option>';
					s+=	'<option value = "长期">长期</option>';
					s+=	'<option value = "短期">短期</option>';
					s+=	'<option value = "3年">3年</option>';
					s+=	'<option value = "5年">5年</option>';
					s+=	'<option value = "10年">10年</option>';
					s+=	'<option value = "15年">15年</option>';
					s+=	'<option value = "25年">25年</option>';
					s+=	'<option value = "30年">30年</option>';
					s+=	'</select><input type="text" id="rightPut" name="validdate" style="margin-top:-25px ;width:110px;"value="永久" onfocus="this.select();"/></div>';
					obj.replaceWith(s);*/
					obj.click(function(){
						var offset=obj.offset();
						$('#deadline').show().offset({top:offset.top+16,left:offset.left});//保管期限列表
						$("#deadline li").click(function(){
							obj.val($(this).html());
						});
						});
			}
			
		})
$("body").bind("mousedown", clickBodyDown);
</script>

