<table id='accountInfoTab'></table>
<script type="text/javascript">
	var classificationName='<?php echo $classificationNameVal;?>';
	var accountingPeriod='<?php echo $accountingPeriodVal;?>';
	var yearMonth='<?php echo $yearMonthVal;?>';
	var path='<?php echo $path;?>';
	var resultLen='<?php echo $resultLen;?>';
	
	//根据浏览器的类型自动调整整体的宽、高
	var __width;
	if(resultLen>=10){
		__width=885+42;
	}else{
		__width=868+42;
	}
	if (window.ActiveXObject) {
		if (navigator.userAgent.indexOf("MSIE 6.0") > 0) {
			__width = __width - 2;
		}else if (navigator.userAgent.indexOf("MSIE 7.0") > 0) {
			if(resultLen>8){
				__width = __width+1;
			}
		}else if (navigator.userAgent.indexOf("MSIE 8.0") > 0) {
			__width = __width - 8;
		}else if (navigator.userAgent.indexOf("MSIE 9.0") > 0) {
			if(resultLen>10){
				__width=878+41;
			}else{
				__width=861+41;
			}
		}
	}
	$("#accountInfoTab").flexigrid({
		url:$.appClient.generateUrl({ESIdentify:'showResultList',path:path,classificationNameVal:encodeURI(classificationName),accountingPeriodVal:accountingPeriod,yearMonthVal:yearMonth},'x'),
		dataType: 'json',
		colModel: [
				{display: '序号',name:'num',width:30,align:'center',metadata:'num'},
				{display: '操作',name:'operating',width:30,align:'center'},
				{display: '会计期间',name:'accountingPeriod',width:60,align:'center',metadata:'accountingPeriod'},
				{display: '凭证类型',name:'recordType',width:100,align:'left',metadata:'recordType'},
				{display: '公司名称',name:'companyName',width:120,align:'left',metadata:'companyName'},
				{display: '最小凭证号',name:'recordIdMin',width:150,align:'left',metadata:'recordIdMin'},
				{display: '最大凭证号',name:'recordIdMax',width:150,align:'left',metadata:'recordIdMax'},
				{display: '本期凭证数量',name:'shouldReceive', width :80,align:'right',metadata:'shouldReceive'},  
				{display: '导入数量',name:'receive',width:80,align: 'right',metadata:'receive'}
				//{display: '附件是否完整',name:'electronicAttachmentStatus',width:90,align:'center',metadata:'electronicAttachmentStatus'}
		],
		useRp: true,
		width: __width,
		height: 250
	});
</script>