<link href="" rel="stylesheet" type="text/css">
<hr width="100%">
<input type="radio" name="print_style" value="excel">文书档案案卷目录（A4，2行）<br>
<input type="radio" name="print_style" value="excel">文书档案案卷目录（A4，3行）<br>
<input type="radio" name="print_style" value="excel">中国联通归档文件目录（PDF）<br>
<input type="radio" name="print_style" value="excel">原网通文书档案案卷目录（Word）<br>
<span>报表格式选择</span>
<hr width="100%">
<input type="radio" name="print_style" value="PDF">PDF<br>
<input type="radio" name="print_style" value="excel">Excle<br>
<input type="radio" name="print_style" value="word">Word<br>
<span>打印数据筛选</span>
<hr width="100%">
<table width="800" >
	<tr>
		<td>字段名</td>
		<td>比较符</td>
		<td>字段值</td>
		<td>关系符</td>
		<td>增加行</td>
		<td>删除行</td>
	</tr>
	<tr>
		<td> <select name="">
				<option value="">题目</option>
				<option value="">文号</option>
				<option value="">分类号</option>
				<option value="">日期</option>
				<option value="">责任人</option>
				<option value="">主题词</option>
			</select></td>
		<td> <select name="">
				<option value="">等于</option>
				<option value="">大于</option>
				<option value="">小于</option>
				<option value="">不等于</option>
				<option value="">大于等于</option>
				<option value="">小于等于</option>
				<option value="">包含</option>
				<option value="">不包含</option>
			</select></td>
		<td><input type="text" value="" name=""></td>
		<td><select name="">
				<option value="">并且</option>
				<option value="">或者</option>
				</select></td>
		<td><span>添加</span></td>
		<td>删除</td>
	</tr>
</table>
