<!-- wangbo 20140424 -->
<script
	type="text/javascript" src="<?php echo $tplPath;?>/ESRole/js/ESRole.js"></script>
<script
	type="text/javascript" src="<?php echo $tplPath;?>/ESRole/js/button.js"></script>
<link
	href="<?php echo $tplPath?>/ESRole/css/style.css" rel="stylesheet"
	type="text/css">
<script>
$(document).ready(function(){
		$("#roleGrid").flexigrid({url :$.appClient.generateUrl({ESRole: 'findRoleList',appId:<?php echo isset($appID)?$appID:'0'?>}, 'x'),
			dataType : 'json',
			colModel : [ 
            {display : '',name : 'startNum',width : 30,align : 'center'}, 
		    {display : '<input type="checkbox" id="roleServerIdList">',name : 'ids',width : 15,align : 'center'}, 
		    {
				display : '操作',
				name : 'operate',
				width : 30,
				sortable : true,
				align : 'center'
			},{
				display : 'ID',
				name : 'roleId',
				metadata:'roleId',
				width : 40,
				align : 'left'
			}, 
			{
				display : '角色标识',
				name : 'roleCode',
				metadata:'roleCode',
				width : 80,
				align : 'left'
			},{
				display : '角色名称',
				name : 'roleName',
				metadata:'roleName',
				width : 80,
				align : 'left'
			},
			 {
				display : '创建时间',
				name : 'createTime',
				metadata:'createTime',
				width : 100,
				align : 'left'
			}, 
			 {
				display : '修改时间',
				name : 'updateTime',
				metadata:'updateTime',
				width : 100,
				sortable : true,
				align : 'left'
			}, {
				display : '是否为系统角色',
				name : 'isSystem',
				metadata:'isSystem',
				width : 110,
				sortable : true,
				align : 'center',
				process:formatValue
			},{
				display : '角色描述',
				name : 'roleRemark',
				metadata:'roleRemark',
				width : 300,
				align : 'left'
			}],
			buttons : [ {
				name : '添加',
				bclass : 'add',
				onpress : add_role
			}, {
				name : '删除',
				bclass : 'delete',
				onpress : delete_role
			}],
			singleSelect:true,
			usepager : true,
			title : '角色管理',
			useRp : true,
			rp : 20,
			nomsg : "没有数据",
			showTableToggleBtn : false,
			pagetext : '第',
			outof : '页 /共',
			width : 'auto',
			height : 'auto',
			pagestat : ' 显示 {from} 到 {to}条 / 共{total} 条' 
		});
		function sizeChanged(){
			if($.browser.msie && $.browser.version==='6.0'){
				$("html").css({overflow:"hidden"});
			}
			var h = $(window).height() - $("#eslist").position().top;
			var flex = $("#roleGrid").closest("div.flexigrid");
			var bDiv = flex.find('.bDiv');
		    var contentHeight = bDiv.height();
		    var headflootHeight = flex.height() - contentHeight; 
		    bDiv.height(h - headflootHeight);
			flex.height(h);
			// 修改IE表格宽度兼容
			if($.browser.msie && $.browser.version==='6.0'){
				flex.css({width:"-=3px"});
			}
		};
		sizeChanged();
		$('div[class="tDiv2"]').append('<div class="find-dialog"><input id="keyWord" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="keyWord" value="请输入关键字" /><span onclick="roleQuery()"></span></div>');
		 function formatValue(tdDiv){
				if(tdDiv.innerHTML=='1')
					tdDiv.innerHTML='是';
				else 
					tdDiv.innerHTML='否';
		};
		//全选
		$("#roleServerIdList").die().live('click',function(){
			$("input[name='roleServerId']").attr('checked',$(this).is(':checked'));
		});
		var roleCodeZZ =/^[A-Za-z]+$/;
		//添加角色
		function add_role(){
			var appId;
			var treeObj = $.fn.zTree.getZTreeObj("appTreeDemo");
			if(treeObj!=null){
				var nodes = treeObj.getSelectedNodes();
				if(nodes.length<=0){
                      return ;
				}else if(nodes[0].name=="应用列表"){
                      return ;
				}
				appId = nodes[0].appId;
			}else{
				 appId = <?php echo isset($appID)?$appID:'0'?>;
			}
			$.ajax({
			        url : $.appClient.generateUrl({
					ESRole : 'add_role',appId:appId},'x'),
				    success:function(data){
					    	$.dialog({
						    	title:'添加角色',
						    	modal:true, //蒙层（弹出会影响页面大小） 
					    	   	fixed:false,
					    	   	stack: true ,
					    	    resize: false,
					    	    lock : true,
								opacity : 0.1,
						    	okVal:'保存',
							    ok:true,
							    cancelVal: '关闭',
							    cancel: true,
							    content:data,
							    ok:function()
						    	{
							    	var roleCode = $("#addRole input[name='roleCode']").val(); 
							    	var roleName = $("#addRole input[name='roleName']").val(); 
							    	var roleData = $("#addRole").serialize(); 
							    	var Actionurl = $.appClient.generateUrl({ESRole : 'addRole'}, 'x');
							    	if(roleCode==""||roleName==""){
							    		if(roleCode=='')
							    			$("#addRole input[name='roleCode']").addClass("warnning");
							    		if(roleName=='')
							    			$("#addRole input[name='roleName']").addClass("warnning");
							    		return false;
							    	}else if(roleCodeZZ.test(roleCode)==false){
							    		$("#addRole input[name='roleCode']").addClass("warnning");
							    		return false;
							    	}else{
								    	$.post(Actionurl,{data : roleData}, function(res){
					        				if (res == 'true') {
					        					$.dialog.notice({icon : 'succeed',content : '添加成功',title : '3秒后自动关闭',time : 3});
					        					$("#roleGrid").flexReload();
					        					return;
					        				} else {
					        					$.dialog.notice({icon : 'error',content : '添加失败',title : '3秒后自动关闭',time : 3});
					        					$("#roleGrid").flexReload();
					        					return;
					        				}
					        			});
								    }
							    }
						    });
					    },
					    cache:false
				});
	     } 
	     //删除角色
		function delete_role(){
			var treeObj = $.fn.zTree.getZTreeObj("appTreeDemo");
			if(treeObj!=null){
				var nodes = treeObj.getSelectedNodes();
				if(nodes.length<=0){
                      return ;
				}else if(nodes[0].name=="应用列表"){
                      return ;
				}
				appId = nodes[0].appId;
			}
			var checkboxlength = $('#roleGrid input:checked').length;
			if (checkboxlength == 0) {
				$.dialog.notice({icon : 'warning',content : '请选择要删除的数据！',time : 3});
				return;
			}
			$.dialog({
				content : '确定要删除吗？删除后不能恢复！',
				okVal : '确定',
				ok : true,
				cancelVal : '关闭',
				cancel : true,
				ok : function() {
					var idStr = '';
					$('#roleGrid input:checked').each(
						function(i) {
							idStr += $('#roleGrid input:checked:eq(' + i+ ')').val()+ ',';
						});
					    idStr=idStr.substring(0,idStr.length-1);
						var url = $.appClient.generateUrl({ESRole : 'deleteRoleList'}, 'x');
						$.post(url, {data : idStr}, function(res) {
							if(res=='true'){
								$.dialog.notice({
									icon : 'succeed',
									content :'删除成功！',
									time : 3
								});
								$("#roleGrid").flexReload();
								return;
							}else{
								$.dialog.notice({icon : 'warning',
									content :'不允许删除',
									time : 3
								});
								$("#roleGrid").flexReload();
								return;
							}
						});
				}
			});
		}
		//编辑角色
		function edit_role(tr){
			var columns = ['roleId','roleCode','roleName','isSystem','roleRemark'];
			var colValues = $("#roleGrid").flexGetColumnValue(tr,columns);
			var colValuesArray = colValues.split("|");
			if(colValuesArray[3]=="是"){//系统角色不允许修改
                       return;
			}
			$.ajax({
				    url : $.appClient.generateUrl({ESRole : 'edit_role',data:colValues},'x'),
				    success:function(data){
					     $.dialog({
						    	title:'编辑角色',
					    	   	fixed:false,
					    	    resize: false,
					    	    lock : true,
								opacity : 0.1,
						    	content:data,
							    cancelVal: '关闭',
							    cancel: true,
							    okVal:'保存',
							    ok:true,
							    ok:function()
						    	{
							    	var roleCode = $("#editRole input[name='roleCode']").val(); 
							    	var roleName = $("#editRole input[name='roleName']").val(); 
							    	var Actionurl = $.appClient.generateUrl({ESRole : 'addRole'}, 'x');
							    	var roleData = $("#editRole").serialize();
							    	if(roleCode==""||roleName==""){
							    		if(roleCode=='')
							    			$("#editRole input[name='roleCode']").addClass("warnning");
							    		if(roleName=='')
							    			$("#editRole input[name='roleName']").addClass("warnning");
							    		return false;
							    	}else if(roleCodeZZ.test(roleCode)==false){
							    		$("#editRole input[name='roleCode']").addClass("warnning");
							    		return false;
							    	}else{
							    		$.post(Actionurl,{data : roleData}, function(res){
							    			if (res == 'true') {
							    				$.dialog.notice({icon : 'succeed',content : '修改成功',title : '3秒后自动关闭',time : 3});
							    				$("#roleGrid").flexReload();
							    				return;
							    			} else {
							    				$.dialog.notice({icon : 'error',content : '修改失败',title : '3秒后自动关闭',time : 3});
							    				return;
							    			}
							    		});
								    }
								 }
						    });
					    },
					    cache:false
				});
			}
		$(".editbtn").die().live("click", function(){
			edit_role($(this).closest("tr"));
		});  
		function roleQuery(){
			var appId;
			var treeObj = $.fn.zTree.getZTreeObj("appTreeDemo");
			if(treeObj!=null){
				var nodes = treeObj.getSelectedNodes();
				if(nodes.length<=0){
                     return ;
				}else if(nodes[0].name=="应用列表"){
                     return ;
				}
				appId = nodes[0].appId;
			}else{
				 appId = <?php echo isset($appID)?$appID:'0'?>;
			}
			var keyword=$.trim($('input[name="keyWord"]').val());
			if(keyword=='' || keyword=='请输入关键字') {
				keyword = '';
			}
			var url=$.appClient.generateUrl({ESRole: 'findRoleList',appId:appId,keyWord:keyword},'x');
			$("#roleGrid").flexOptions({url:url}).flexReload();
			return false;
		}
		$(document).keydown(function(event){
			if(event.keyCode == 13 && document.activeElement.id == 'keyWord') {
				roleQuery();
			}
		});
});
</script>
    <div id="eslist">
        <table id="roleGrid"></table> 
 	</div> 
 
 