<link rel="stylesheet" href="<?php echo $tplPath;?>/public/SWFUpload/css/swfupload.css" type="text/css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/swfupload.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/swfupload.queue.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/fileprogress.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/SWFUpload/js/handlers.js"></script>
<form id="editUser" action="" method="post">
	<div class="estransfer">
		<input type="hidden" name="roleIds" value="">
		<ul>
			<li>
				<span>用户名<font color="red" size="3">*</font></span>
				<input type="text" name="userid" readonly="readonly" value="<?php echo $data[1];?>">
				<input type="hidden" id="editUserid" name="id" value="<?php echo $data[0];?>">
			</li>
			<li>
				<span>姓<font color="red" size="3">*</font></span>
				<input type="text" name="lastname" value="<?php   echo $data[2];?>">
			</li>
			<li>
				<span>名<font color="red" size="3">*</font></span>
				<input type="text" name="firstname" value="<?php echo $data[3];?>">
			</li>
			<li style="display:none"><span>状态<font color="red" size="3">*</font></span> 
				<select	name="userstatus">
					<option <?php echo  ($data[4]=="1"||$data[4]=="启用")?'selected':'' ; ?> value='1'>启用</option>
					<option <?php echo  ($data[4]=="0"||$data[4]=="禁用")?'selected':'' ; ?> value='0'>禁用</option>
				</select>
			</li>
			<li>
				<span>手机<font color="red" size="3">*</font></span>
				<input type="text" name="mobtel" value="<?php echo $data[5];?>">
			</li>
			<li>
				<span>邮件</span>
				<input type="text" name="emailaddress" value="<?php echo $data[6];?>">
			</li>
		</ul>
	</div>
</form>
<div id="eslistEditUser" style="width: 600; margin-top: 25px;">
	<table id="editUserRoleGrid"></table>
</div>
<script type="text/javascript">
var emailaddressZZ = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
var nameZZ= /^[\u4e00-\u9fa5a-zA-Z]+$/;
var mobtelZZ =/^1[3|4|5|8][0-9]\d{8}$/;
var lengthZZ= /.{51}|^\s*$/g;
 $("#editUser input[name='emailaddress']").bind('blur',function(){
 	var emailaddress = $(this).val();
 	emailaddress=emailaddress.replace(/[ ]/g,"");
 	if(emailaddress==''){
 		return false;
 	}
 	if(emailaddressZZ.test(emailaddress)==false){
 		$(this).addClass("warnning");
 		$(this).attr("title","格式不正确");
 		return false;
 	}
 	if(lengthZZ.test(emailaddress)==true){
 		$(this).addClass("warnning");
 		$(this).attr("title","邮箱长度不能超过50个字符");
 		return false;
 	}
 	$(this).removeClass("warnning");
 });
 $("#editUser input[name='mobtel']").bind('blur',function(){
	 	var mobtel = $(this).val();
	 	mobtel=mobtel.replace(/[ ]/g,"");
	 	if(mobtel==''){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","不能为空");
	 		return false;
	 	}
	 	if(mobtelZZ.test(mobtel)==false){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","格式不正确");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#editUser select[name='userstatus']").bind('change',function(){
		var userstatus = $(this).val();
		userstatus=userstatus.replace(/[ ]/g,"");
		if(userstatus==''){
			$(this).addClass("warnning");
			$(this).attr("title","不能为空");
			return false;
		}
		$(this).removeClass("warnning");
	});
 $("#editUser input[name='firstname']").bind('blur',function(){
	 	var firstname = $(this).val();
	 	firstname=firstname.replace(/[ ]/g,"");
	 	if(firstname==''){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","不能为空");
	 		return false;
	 	}
	 	if(nameZZ.test(firstname)==false){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","请输入汉字或英文字母");
	 		return false;
		 	}
	 	if(lengthZZ.test(firstname)==true){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","姓氏长度不能超过50个字符");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#editUser input[name='lastname']").bind('blur',function(){
	 	var lastname = $(this).val();
	 	lastname=lastname.replace(/[ ]/g,"");
	 	if(lastname==''){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","不能为空");
	 		return false;
	 	}
	 	if(nameZZ.test(lastname)==false){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","请输入汉字或英文字母");
	 		return false;
		 	}
	 	if(lengthZZ.test(lastname)==true){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","名字长度不能超过50个字符");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#editUser input[name='userid']").bind('blur',function(){
	 	var userid = $(this).val();
	 	userid=userid.replace(/[ ]/g,"");
	 	if(userid==''){
	 		$(this).addClass("warnning");
	 		$(this).attr("title","不能为空");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
$(document).ready(function(){
	    $("#editUserRoleGrid").flexigrid({url :false,
			dataType : 'json',
			colModel : [ 
            {display : '',name : 'startNum',width : 30,align : 'center'}, 
			{display : '<input type="checkbox" id="editUserRoleList">',name : 'ids',width : 50,align : 'center'},
			{
				display : 'ID',
				name : 'roleId',
				metadata:'roleId',
				width : 30,
				align : 'left',
				hide:true
			}, {
				display : '角色标示',
				name : 'roleCode',
				metadata:'roleCode',
				width : 80,
				align : 'left'
			},{
				display : '角色名称',
				name : 'roleName',
				metadata:'roleName',
				width : 80,
				align : 'left'
			},{
				display : '创建时间',
				name : 'createTime',
				metadata:'createTime',
				width : 60,
				align : 'left'
			}, 
			 {
				display : '修改时间',
				name : 'updateTime',
				metadata:'updateTime',
				width : 60,
				sortable : true,
				align : 'left'
			}, {
				display : '是否为系统角色',
				name : 'isSystem',
				metadata:'isSystem',
				width : 80,
				sortable : true,
				align : 'center',
				process:formatValue
			},{
				display : '角色描述',
				name : 'roleRemark',
				metadata:'roleRemark',
				width : 600,
				align : 'left'
			}],
// 				buttons : [{
// 					name : '添加',
// 					bclass : 'add',
// 					onpress : addRoleToUserOnEdit
// 				},{
// 					name : '删除',
// 					bclass : 'delete',
// 					onpress : delRoleFromUserOnEdit
// 				}],
				singleSelect:true,
				usepager : true,
				title : '',
				useRp : true,
				rp : 20,
				nomsg : "没有数据",
				showTableToggleBtn : false,
				pagetext : '第',
				outof : '页 /共',
				width : 'auto',
				height : 'auto',
				pagestat : ' 显示 {from} 到 {to}条 / 共{total} 条' 
		});
	    function formatValue(tdDiv){
			if(tdDiv.innerHTML=='1')
				tdDiv.innerHTML='是';
			else 
				tdDiv.innerHTML='否';
		};
		function sizeChanged(){
			if($.browser.msie && $.browser.version==='6.0'){
				$("html").css({overflow:"hidden"});
			}
			var h = $(window).height() - $("#eslistEditUser").position().top;
			var flex = $("#editUserRoleGrid").closest("div.flexigrid");
			var bDiv = flex.find('.bDiv');
		    var contentHeight = bDiv.height();
		    var headflootHeight = flex.height() - contentHeight; 
		    bDiv.height(200 - headflootHeight);
			flex.height(200);
			flex.width(560);
			// 修改IE表格宽度兼容
			if($.browser.msie && $.browser.version==='6.0'){
				flex.css({width:"-=3px"});
			}
		};
		sizeChanged();
		$('#eslistEditUser div[class="tDiv2"]').append('<div class="find-dialog"><input id="editUserRoleKeyWord" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="editUserRoleKeyWord" value="请输入关键字" /><span onclick="getEditUserRoleQuery()"></span></div>');
		//全选
		$("#editUserRoleList").die().live('click',function(){
			$("input[name='userRoleListId']").attr('checked',$(this).is(':checked'));
		});
		var url = $.appClient.generateUrl({ESOrgAndUser : 'getUserRoles'}, 'x');
		$.post(url,{userId:'<?php echo $data[0];?>'}, function(res){
			  if(res==''){
                   
			   }else{
				   selectedIds = res;
				   mark = true;
				   $("#editUserRoleGrid").flexOptions({url:$.appClient.generateUrl({ESOrgAndUser: 'findUserRole',selectedRoleId:res}, 'x')}).flexReload();
			   }
		});
});
/** wanghongchen 20140930 头像上传 **/
function createSWFUpload(){
	var addhtml = '';
	var fileLimit="102400";
	var fileType="*.png;*.jpg;*.jpeg;*.bmp;";
	var upload = new SWFUpload({
		//提交路径
		upload_url: "",
		//向后台传递额外的参数
		//提交到服务器的参数信息，这样就添加了一个param参数，值是uploadParams在服务器端用request.getParameter(“param”)就可以拿到值
		//上传文件的名称
		file_post_name: "file.jpg",
		file_size_limit : fileLimit,	// 100MB
		file_types : fileType,
		file_types_description : "文件类型",
		file_upload_limit : "1",
		file_queue_limit : "0",

		// 事件处理
		swfupload_loaded_handler : swfuploadLoaded,
		file_dialog_start_handler : fileDialogStart,
		file_queued_handler : fileQueued,
		file_queue_error_handler : fileQueueError,
		file_dialog_complete_handler : fileDialogComplete,
		upload_start_handler : uploadStart,
		upload_progress_handler : uploadProgress,
		upload_error_handler : uploadError,
		upload_success_handler : uploadSuccess,
		upload_complete_handler : uploadComplete,

		// 按钮的处理
		button_image_url : "<?php echo $tplPath?>/public/SWFUpload/img/ButtonUpload72.png",
		button_placeholder_id : "btnAdd",
		button_width: 72,
		button_height: 28,
		// Flash文件地址设置
		flash_url : "<?php echo $tplPath?>/public/SWFUpload/js/swfupload.swf",
		custom_settings : {
			progressTarget : "fsUploadProgress",
			cancelButtonId : "btnCancel",
			startButtonId : "btnStart",
			// 上传成功的回调函数
			uploadSuccess : function(file, data){
				var data = $.parseJSON(data);
				if(data.success == 'false'){ return false;}
				$.ajax({
					url: $.appClient.generateUrl({ESAppClientBanner:'getBannerUrl'},'x'),
					data: { mark:  data.fileId+'.'+data.type , index:'true'},
					type: 'POST',
					async: false, 
					success: function(url){
						$('#selfIcon').attr('src',url);
						art.dialog.list['updateImageFileDialog'].close();
						$.ajax({
							url:$.appClient.generateUrl({ESOrgAndUser:'saveHeaderImageId'},'x'),
							type:'post',
							data:{fileId:data.fileId},
							success:function(){
								$.dialog.notice({icon : 'succeed',content : '头像修改成功！'});
							}
						});
					}
				});

			}
		}
	});
	$("#btnCancel").click(function(){cancelQueue(upload);});
	$("#btnStart").click(function(){
			$.post($.appClient.generateUrl({ESIdentify:'getUploadURL'},'x'),  function(data){
				upload.setUploadURL(data);
				startQueue(upload);
			});
	});

};
</script>