<div id='modifyPasswordDIV' class = "enitformCls">
	<label style = "float:left;">旧密码：</label><input id='oldPassword' name='oldPassword' type='password' style = "float:right;width:180px;">
	<div style = "clear:both"></div>
	<label style = "float:left;">新密码：</label><input id='newPassword' name='newPassword' type='password' style = "float:right;width:180px;">
	<div style = "clear:both"></div>
	<label style = "float:left;">确认密码：</label><input id='repetPassword' name='repetPassword' type='password' style = "float:right;width:180px;">
</div>
<style>
.enitformCls{
	width:250px;
}
</style>
<script type="text/javascript">
	$("#modifyPasswordDIV input[name='repetPassword']").bind('keyup',function(){//用于校验两次密码是否一致
		var repetPassword = $(this).val();
		var newPassword = $("#modifyPasswordDIV input[name='newPassword']").val();
		if(repetPassword != newPassword){
			$("#modifyPasswordDIV input[name='repetPassword']").addClass("warnning");
		}else{
			$("#modifyPasswordDIV input[name='repetPassword']").removeClass("warnning");
		}
	});
	$("#modifyPasswordDIV input[name='newPassword']").bind('keyup',function(){//用于校验两次密码是否一致
		var newPassword = $(this).val();
		var repetPassword = $("#modifyPasswordDIV input[name='repetPassword']").val();
		if(repetPassword != newPassword){
			$("#modifyPasswordDIV input[name='repetPassword']").addClass("warnning");
		}else{
			$("#modifyPasswordDIV input[name='repetPassword']").removeClass("warnning");
		}	
	});


</script>