<meta http-equiv="content-type" content="text/html; charset=utf-8">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/DatePicker/WdatePicker.js"></script>
<link rel="stylesheet" href="<?php echo $tplPath ?>/public/ztree/css/zTreeStyle/zTreeStyle.css" type="text/css">
<link rel="stylesheet" href="<?php echo $tplPath ?>/public/ztree/css/zTreeStyle/zTreeTbar.css" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/cookie.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/flexigrid/css/flexigrid.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/flexigrid/js/flexigrid.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<?php echo $app->draw('nav',array('esaction'=>$esaction, 'app'=>$app));?>
<?php echo $app->draw('appmenu',array('esaction'=>$esaction, 'app'=>$app, 'expand'=>2));?>

<link rel="stylesheet" href="<?php echo $tplPath ?>/ESFormAccredit/css/style.css" type="text/css">
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFormAccredit/js/init.js"></script>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFormAccredit/js/formAccredit.js"></script>
<script>
$(document).ready(function(){
	$("#estabs").esTabs("open", {title:"表单授权", content:"#formAccreditDataGridDiv"});
});
</script>
<div class='formAccredit_main'>
	<div id='formAccreditDataGridDiv' class='formAccredit_grid'>
		<table id='formAccreditDataGrid'></table>
	</div>
</div>