<style>
.ztree li a span{
	color:#444;
}
</style>
<script type="text/javascript" src="<?php echo $tplPath;?>/ESFormBuilder/js/relationWorkFlow.js"></script>
<div id="formBuilder_manager_main_relation" class='formBuilder_manager_main_relation' formId='<?php echo $data[0];?>'>
	<div id='formBuilder_model_type_relation' class='formBuilder_model_tree'>
		<div id='formBuilderTypeTree_relation' class='ztree'></div>
	</div>
	<div id='formBuilderDataGridDiv_relation' class='formBuilder_model_grid'>
		<table id='formBuilderDataGrid_relation'></table>
	</div>
</div>