<!-- wangbo 20140403-->
<form id="addUser" action=""	method="post">
<div class="estransfer">
<ul>
<li><span>用户名<font color="red" size="3">*</font></span><input  type="text" name="userid"   title="例如:xxx.xxx.xxx.xxx"   value="">
<input type="hidden" name="id"    value="-1"  >
<input type="hidden" name="appid"    value= "<?php echo $data[0];?>" >
<input type="hidden" name="orgcode"     value= "<?php echo $data[1];?>">
<input type="hidden" name="orgseq"    value= "<?php echo $data[2];?>">
<input type="hidden" name="roleIds"    value= "">
</li>
<li><span>姓<font color="red" size="3">*</font></span><input  type="text" name="lastname"   title="例如:xxx.xxx.xxx.xxx"   value=""></li>
<li><span>名<font color="red" size="3">*</font></span><input type="text" name=firstname  title="例如:8080"  value=""></li>
<li><span>密码<font color="red" size="3">*</font></span><input type="password" name="password"  title="例如:8080"  value=""></li>
<li><span>密码确认<font color="red" size="3">*</font></span><input type="password" name="passwordconfirm"  title="例如:8080"  value=""></li>
<li><span>状态<font color="red" size="3">*</font></span><select name="userstatus" ><option value=''>--请选择--</option><option value='1'>启用</option><option value='0'>禁用</option></select></li>
<li><span>手机<font color="red" size="3">*</font></span><input type="text" name="mobtel"  title="例如:D:\flyingsoft" value=""></li>
<li><span>邮件<font color="red" size="3">*</font></span><input type="text" name="emailaddress"  title="例如:D:\flyingsoft" value=""></li>
</ul>
</div>
</form>
<div id="eslist"   style="width: 600;margin-top:25px;border-top:solid 1px #ccc">
		<table id = "userRoleGrid"></table>
</div>
 <script type="text/javascript">
 var emailaddressZZ = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
 var mobtelZZ =  /^1[3|4|5|8][0-9]\d{8}$/;
 $("#addUser input[name='emailaddress']").bind('blur',function(){
 	var emailaddress = $(this).val();
 	emailaddress=emailaddress.replace(/[ ]/g,"");
 	if(emailaddress==''){
 		$(this).addClass("warnning");
 		return false;
 	}
 	if(emailaddressZZ.test(emailaddress)==false){
 		$(this).addClass("warnning");
 		return false;
 	}
 	$(this).removeClass("warnning");
 });
 $("#addUser input[name='mobtel']").bind('blur',function(){
	 	var mobtel = $(this).val();
	 	mobtel=mobtel.replace(/[ ]/g,"");
	 	if(mobtel==''){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	if(mobtelZZ.test(mobtel)==false){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#addUser select[name='userstatus']").bind('change',function(){
		var userstatus = $(this).val();
		userstatus=userstatus.replace(/[ ]/g,"");
		if(userstatus==''){
			$(this).addClass("warnning");
			return false;
		}
		$(this).removeClass("warnning");
	});
 $("#addUser input[name='passwordconfirm']").bind('blur',function(){
	 	var passwordconfirm = $(this).val();
	 	passwordconfirm=passwordconfirm.replace(/[ ]/g,"");
	 	if(passwordconfirm==''){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	if(passwordconfirm!=$("#addUser input[name='password']").val()){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#addUser input[name='password']").bind('blur',function(){
	 	var password = $(this).val();
	 	password=password.replace(/[ ]/g,"");
	 	if(password==''){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#addUser input[name='firstname']").bind('blur',function(){
	 	var firstname = $(this).val();
	 	firstname=firstname.replace(/[ ]/g,"");
	 	if(firstname==''){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#addUser input[name='lastname']").bind('blur',function(){
	 	var lastname = $(this).val();
	 	lastname=lastname.replace(/[ ]/g,"");
	 	if(lastname==''){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
 $("#addUser input[name='userid']").bind('blur',function(){
	 	var userid = $(this).val();
	 	userid=userid.replace(/[ ]/g,"");
	 	if(userid==''){
	 		$(this).addClass("warnning");
	 		return false;
	 	}
	 	$(this).removeClass("warnning");
	 });
$(document).ready(function(){
	 $("#userRoleGrid").flexigrid({url :false,
			dataType : 'json',
			colModel : [ 
               {display : '',name : 'startNum',width : 30,align : 'center'}, 
			   {display : '<input type="checkbox" id="userRoleList">',name : 'ids',width : 50,align : 'center'},
               {display : '角色名称',name : 'roleName',width : 50,align : 'center'}, 
               {display : '角色描述',name : 'roleRemark',width : 150,align : 'center'},
               {display : '角色类型',name : 'isSystem',width : 80,align : 'center',process:formatRole}],
				buttons : [{
					name : '添加',
					bclass : 'add',
					onpress : addRoleToUser
				},{
					name : '删除',
					bclass : 'delete',
					onpress : delRoleFromUser
				}],
				singleSelect:true,
				usepager : true,
				title : '控制台服务管理',
				useRp : true,
				rp : 20,
				nomsg : "没有数据",
				showTableToggleBtn : false,
				pagetext : '第',
				outof : '页 /共',
				width : 'auto',
				height : 'auto',
				pagestat : ' 显示 {from} 到 {to}条 / 共{total} 条' 
		});
		function sizeChanged(){
			if($.browser.msie && $.browser.version==='6.0'){
				$("html").css({overflow:"hidden"});
			}
			var h = $(window).height() - $("#eslist").position().top;
			var flex = $("#userRoleGrid").closest("div.flexigrid");
			var bDiv = flex.find('.bDiv');
		    var contentHeight = bDiv.height();
		    var headflootHeight = flex.height() - contentHeight; 
		    bDiv.height(200 - headflootHeight);
			flex.height(200);
			flex.width(560);
			// 修改IE表格宽度兼容
			if($.browser.msie && $.browser.version==='6.0'){
				flex.css({width:"-=3px"});
			}
		};
		sizeChanged();
		$('div[class="tDiv2"]').append('<div class="find-dialog"><input id="userRoleKeyWord" onblur="if($(this).val()==\'\')$(this).val(\'请输入关键字\')" onfocus="if($(this).val()==\'请输入关键字\')$(this).val(\'\')" type="text" name="userRoleKeyWord" value="请输入关键字" /><span onclick="getUserRoleQuery()"></span></div>');
		//全选
		$("#userRoleList").die().live('click',function(){
			$("input[name='userRoleListId']").attr('checked',$(this).is(':checked'));
		});
});
</script>
 