<table id="archivemain"></table>
<!-- xiewenda 20141010 加入电子文件显示时调用函数文件和显示样式文件 -->
<script type="text/javascript" src="<?php echo $tplPath;?>/ESIdentify/js/common.js"></script>
<link rel="stylesheet" href="<?php echo $tplPath;?>/ESIdentify/css/viewfile.css" type="text/css"/>
<script type="text/javascript">
$(function(){
	$("#archivemain").flexigrid({
		url:$.appClient.generateUrl({ESIdentify:'set_json2',path:'<?php echo $path;?>'}),
		dataType: 'json',
		colModel : [
			{display: '序号', name : 'num', width : 20, align: 'center'},
			{display: '<input type="checkbox" name="path" />', name : 'ids', width : 40, align: 'center'},
			{display: '原文标识', name : 'operate', width : 50, align: 'left',freeze:true},
			<?php echo $fields;?>
		],
		usepager: true,
		useRp: true,
		rp: 20,
		nomsg:"没有数据",
		showTableToggleBtn: false,
		pagetext: '第',
		outof: '页 /共',
		width: 'auto',
		height: 322,
		pagestat:' 显示 {from} 到 {to}条 / 共{total} 条'
	});   
	
	$('#archivemain tr').die().live('click',function(){
		$('input[name="path"]').attr("checked",false);
		$(this).find("input[name='path']").attr("checked",true);
	});
	   
});
</script>