<style type="text/css">
	#tbd{border-right:1px solid #ccc;}
.ztree li a span{
	color:#444;
	}
	
</style>

<table id="tb">
	<tr>
		<td id="tbd">
			<div id="filetreebox" style="width:200px;height:380px;overflow:auto;">
				<ul id="archivenav" class="ztree"></ul>
			</div>
		</td>
		<td>
			<div id="borrowlistbox" style="width:600px;height:100%;overflow:auto;">
				
			</div>
		</td>
	</tr>
</table>
<script type="text/javascript">

</script>