<!-- yanghuiqiang 20140526 Loader详细窗口-->
<style>
<!--
#addReport table tr {
	height: 50px;
}
-->
</style>
<div style="">
	<div style="padding-top: 30px;">
		<form id="detail" method="post" enctype="multipart/form-data">
			<table id="table_detail" style="height: 200px;">
				<tr>
					<td><input type="hidden" name="id" id="id"
						value="<?php echo $loader->id;?>"
						style="width: 380px; height: 0px;" /></td>
				</tr>
				<tr>
					<td>是否启用：</td>
					<td><input type="text" name="state" id="state" readOnly=true
						value="<?php echo $loader->state == 1 ? "是" : "否";?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>
				<tr>
					<td>图片：</td>
					<td><img src="<?php echo ($loader->imageUrl);?>" alt="客户端显示图片" height="280px" width="380px"/></td>
				</tr>
				<tr>
					<td>添加时间：</td>
					<td><input type="text" name="time" id="time" readOnly=true
						value="<?php echo $loader->time == "" ? "" : gmdate("Y-m-d H:i:s", ($loader->time / 1000) + 8*3600);?>"
						style="width: 380px; height: 20px;" /></td>
				</tr>
				<tr>
					<td>备注：</td>
					<td><textarea name="describtion" id="describtion" readOnly=true
							style="width: 380px; height: 100px;"><?php echo $loader->describtion;?></textarea>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$('#table_detail input:text').attr("readOnly", true); 
	$('#table_detail textarea').attr("readOnly", true);
});
</script>

