<div class="footer">
  <div class="footerL"><img src="/templates/cu/images/logo_copyright.gif" width="107" height="60" alt="中国联通" /></div>
  <div class="footerR">
     <ul>
      <li><a href="<?php echo url('guide/about.html') ?>">关于云门户</a></li>
      <li><a href="<?php echo url('guide/contacts.html') ?>">运维联系方式</a></li>
      <li><a href="mailto:hq-eipwh@chinaunicom.cn" target="_blank">建议反馈</a></li>
    </ul>
    <p>&copy; 2012 中国联合网络通信有限公司</p>
  </div>
</div>
