<div class="content">
  <div class="left">
    <ul style=" background:none;">
      <li><a href="<?php echo url($this->getUrl('default'));?>">返回<?php echo $title;?></a></li>
      <li class="leftOn bold">布局管理</li>
    </ul>
  </div>
  <div style="width:800px; padding:0px;  float:left;">
    <?php echo $layoutHtml;?>
  </div>
</div>

<script type="text/javascript">
<!--
jQuery(function(){
	$('#recovery_layout').bind('click',function(){
		$.post('/desktop/0/recovery', function(data) {
			if(data == 'ok'){
				alert('操作成功！');
				setTimeout(function(){location.href="/desktop"},1000);
			} else {
				alert('操作失败！');
			}
		});
	})
});
//-->
</script>