<style type="text/css">
.borrowing_message .positionbtn{ width:383px; height:auto; overflow:hidden; float:right;}
</style>
<div class='borrowing_message'>
	<div class='positionbtn'>
		<div class='buttons'>
			<input type='button' value='归还' id="back" class='basebtn basebtn_border  process' />
		</div>
	</div>

	<div class='message_list'>
		<div class='field_s'>
			<p class='like_input'>
				<span>借阅人：</span>
				<input type='text' value="<?php echo $list->borrow_base->manager_reader==''?$list->borrow_base->display_name:$list->borrow_base->manager_reader;?>" readonly='readonly' />
			</p>
			<p class='like_input'>
				<span>利用目的：</span>
				<input type='text' value="<?php echo $list->borrow_base->lymd_f2;?>" readonly='readonly' />
			</p>
		</div>
		<div class='field_s'>
			<p class='like_input'>
				<span>单位：</span>
				<input type='text' value="<?php echo $list->borrow_base->dw_f3;?>" readonly='readonly' />
			</p>
			<p class='like_input'>
				<span>电话：</span>
				<input type='text' value="<?php echo $list->borrow_base->dh_f4;?>" readonly='readonly' />
			</p>
		</div>
		<div class='field_s'>
			<p class='like_input'>
				<span>邮箱：</span>
				<input type='text' value="<?php echo $list->borrow_base->yx_f5;?>" readonly='readonly' />
			</p>
			<p class='like_input'>
				<span>催还提前天数：</span>
				<input type='text' value="<?php echo $list->borrow_base->jysc_f6;?>" readonly='readonly' />
			</p>
		</div>
		<div class='like_textarea'>
			<h2>借阅描述：</h2>
			<textarea readonly='readonly' class='extextarea'><?php echo $list->borrow_base->jyms_f7;?></textarea>
		</div>
	</div>
	<input type="hidden" name="workid" value="<?php echo $list->borrow_base->workflowid;?>" />
	<div class='borrowing_detailed_tbl'><div class='borrowing_detailed_tbl_child'><table id="application"></table></div></div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	var typeArchive = "<?php echo $list->borrow_base->archiveType;?>";
	var ACodeMeta='';
	var titleMeta='';
	if(typeArchive=='accounting'){
		ACodeMeta='RecordID';
		titleMeta='Summary';
	}else if(typeArchive=='document'){
		ACodeMeta='ArchivalCode';
		titleMeta='Title';
	}else if(typeArchive=='contract'){
		ACodeMeta='RecordID';
		titleMeta='Title';
	}/*else if(typeArchive=='technical'){
		ACodeMeta='RecordID';
		titleMeta='Title';
	}else if(typeArchive=='auditfiles'){
		ACodeMeta='RecordID';
		titleMeta='Title';
	}*/
	$.post($.appClient.generateUrl({ESAccountingArchive:'getTagByMetadata'},'x'),{arType:typeArchive,ACodeMeta:ACodeMeta,titleMeta:titleMeta},function(result){
		result=jQuery.parseJSON(result);
		if(result){
			for(var i=0;i<result.length;i++){
				if(result[i].esidentifier==ACodeMeta){
					var ACodeName=result[i].tagChineseName;
				}else if(result[i].esidentifier==titleMeta){
					var titleName=result[i].tagChineseName;
				}
			}
			var modelColum=[
					{display: '序号', name : 'c3', width : 40, sortable : true, align: 'center'},
					{display: ACodeName, name : 'c4', width : 150, sortable : true, align: 'center',metadata:ACodeMeta},
					{display: titleName, name : 'c5', width : 160, sortable : true, align: 'center',metadata:titleMeta},
					{display: '借阅类型', name : 'c6', width : 100, sortable : true, align: 'center'},
					{display: '备注', name : 'c7', width : 180, sortable : true, align: 'center'}
					];
			$("#application").flexigrid({
				dataType: 'json',
				colModel : modelColum,
				usepager: true,
				title: '借阅明细',
				useRp: true,
				rp: 5,
				procmsg:"正在加载，请稍等",
				nomsg:"没有数据",
				resizable:false,
				minColToggle:0,
				showTableToggleBtn: false,
				pagetext: '第',
				outof: '页 /共',
				width: 665,
				height: 160,
				pagestat:' 显示 {from} 到 {to}条 / 共{total} 条'
			});
			var tableurl = $.appClient.generateUrl({ESCollaborative:'get_json'},'x');
			$("#application").flexOptions({newp:1,url:tableurl,query:query}).flexReload();
		}
	});
	$("#back").click(function(){
		var workid = $("input[name='workid']").val();
		var url = $.appClient.generateUrl({ESCollaborative:'doback'},'x');
		$.dialog({
		    	content:"确定要归还么",
		    	okVal:'确定',
		    	cancelVal:'取消',
		    	ok:true,
			    cancel: true,
			    ok:function(){
			    	/*var ext = /\((\d+)\)/;
			    	var val = $("#left_top .turn").text().match(ext)[1];
			    	var newval = Number(val)-1;
			    	var newhtml = "待办业务("+newval+")";
			    	var havedoval = $("#left_top li:eq(2)").text().match(ext)[1];
			    	var newdoval = Number(havedoval)+1;
			    	var havedo = "已办业务("+newdoval+")";*/
			    	$.post(url,{workid:workid},function(result){
						if(result){
							$.dialog.notice({icon:"succeed",content:"归还成功",time:2});
							$("#mylist").flexOptions({newp:1}).flexReload();
							//$("#left_top .turn a").html(newhtml);
							//$("#left_top li:eq(2) a").html(havedo);
							dia.close();
							return;
						}else{
							$.dialog.notice({icon:"error",content:"归还失败",time:2});
						}
						
					});
				}
		});
	
	});
});
</script>
