<style type="text/css">
.borrowing_message .positionbtn{ width:383px; height:auto; overflow:hidden; float:right;}
.checkTime{float:right;margin-right:20px;}
</style>
<div class='borrowing_message'>
	<div class='positionbtn'>
		<div class='buttons'>
			<input type='button' value='流程图' class='basebtn basebtn_border image process' />
		</div>
	</div>

	<div class='message_list'>
		<div class='field_s'>
			<p class='like_input'>
				<span>填报单位：</span>
				<input type='text' name="fillunit" id="fillunit" value="<?php echo $list->yearnewspaper_approval->fillunit;?>" readonly='readonly' />
			</p>
			<p class='like_input'>
				<span>制表人：</span>
				<input type='text' name="lister" id="lister" value="<?php echo $list->yearnewspaper_approval->lister;?>" readonly='readonly' />
			</p>
		</div>
		<div class='field_s'>
			<p class='like_input'>
				<span>年报类型：</span>
				<input type='text' name="datacs" id="datacs" value="<?php echo $list->yearnewspaper_approval->yearnewspaper_type;?>" readonly='readonly' />
			</p>
			<p class='like_input'>
				<span>年度：</span>
				<input type='text' name="fillyear" id="fillyear" value="<?php echo $list->yearnewspaper_approval->fillyear;?>" readonly='readonly' />
			</p>
		</div>
		<div class='field_s'>
			<p class='like_input'>
				<span>浏览附件：</span>
				<span><a id="detailse" href="javascript:void(0);">查看</a></span>
			</p>
		</div>
		<div class='like_textarea'>
			<h2>描述：</h2>
			<textarea readonly='readonly' class='extextarea'><?php echo $list->yearnewspaper_approval->yearnewspaper_desc;?></textarea>
		</div>
		<?php
			foreach ($list->yearnewspaper_opinion as $val){
		?>
			<div class='like_textarea'>
			<h2><?php echo $val->opinion_user_name;?>审批意见：<span class="checkTime"><?php echo $val->opinion_time;?></span></h2>
			<textarea readonly='readonly' class='extextarea'><?php echo $val->opinion_approval;?></textarea>
			</div>
		<?php 
			}
		?>
	</div>
	<input type="hidden" name="workid" value="<?php echo $list->yearnewspaper_approval->workflowid;?>" />
	<!--<input type="hidden" name="taskid" value="<?php echo $list->yearnewspaper_approval->task_id;?>" />-->
	<input type="hidden" name="yearnewspaper_id" id="yearnewspaper_id" value="<?php echo $list->yearnewspaper_approval->yearnewspaper_id;?>" />
</div>
<script type="text/javascript">
	var isComplete="<?php echo $list->iscomplete;?>";
	$(".image").die().live('click',function(){
		var workid = $("input[name='workid']").val();
		if(isComplete==1){
			var url = "<?php echo $tplPath;?>/ESCollaborative/img/bianyan_complete.gif";
		}else{
			var url=$.appClient.generateUrl({ESCollaborative:'imgview', workid:workid},'x');
		}
		var html = '<img src = "'+url+'" />';
		$.dialog({
		    	title:'详细信息',
		    	padding:0,
	    	   	fixed:true,
	    	   	width:580,
	    	   	height:390,
	    	    resize: false,
		    	content:html
		});
	});
	$("#detailse").die().live('click',function(){
		var yearId = $("input[name='yearnewspaper_id']").val();
		var datacs = $("input[name='datacs']").val();
		if(yearId){
			$.ajax({
			    url:$.appClient.generateUrl({ESYearlyReport:'datacs', yearId:yearId},'x'),
			    type:'post',
			    data:'datacs=' + datacs,
			    success:function(data){
			    	$.dialog({
			    		id:"yearDialog",
				    	title:'查看年报',
				    	width:750,
				    	height:500,
				    	padding:'0px',
				    	content:data
				    });
				},
				cache:false
			});
		}
	});
</script>
