<link href='<?php echo $tplPath?>/ESDefault/css/index.css'
	rel="stylesheet">
<link
	href='<?php echo $tplPath?>/ESDefault/css/main.css' rel="stylesheet">
	
<div class='lockscreen' 
	id="mainContentContainer">
	<div class='publicpaper'>
		<h1 sizcache="15" sizset="0">
			<em class="ttl" id='ttlForNew' style="margin: 0 auto 0 auto;"> <?php echo  $info['boardCn'];?>
			</em> 
		</h1>
		<div class='conts'>
			<div class="lineA"></div>
			<ul class='archivelist' id='archivelist'>
				<?php echo $list;?>
			</ul>
			<ul class='papernavigation' id='papernavigation'>
				<?php echo $btn;?>
			</ul>
			<div class="lineH"></div>
		</div>
	</div>
</div>
<script
	type="text/javascript"
	src="<?php echo $tplPath;?>/public/js/jquery.appclient.js?baseurl=<?php echo $esaction->generateUrl(array());?>"></script>
<script
	type="text/javascript"
	src="<?php echo $tplPath;?>/public/artDialog/jquery.artDialog.js?skin=default"></script>
<script
	type="text/javascript"
	src='<?php echo $tplPath?>/ESArchiveShow/js/index.js'></script>
	<script
	type="text/javascript"
	src='<?php echo $tplPath?>/ESArchiveShow/js/pagebtn.js'></script>
<script type='text/javascript'>
$(function(){
	$('#header').hide();
	$('.archivelist').height(620);
	$('#mainContentContainer').css('display','block') ;
	if($('#mainContentContainer').height() < 870){
		$('#mainContentContainer').css('height','870px') ;
	}
	$('#mainContentContainer').css('background-color','rgb(242, 242, 242)');
	$('.publicpaper').css('margin','0 auto 0 auto');
	var alW = $('.publicpaper h1').width();
	var emW = $('.publicpaper h1 em').width();
	$('.publicpaper h1 em').css('padding-left',((alW-emW)/2)+"px");
	$('.publicpaper h1').css('margin-bottom','30px');
	_global.boardId ='<?php echo $info['boardId'];?>';
});
	<?php
		if($info['total']) echo "_pageBtn.bind();";
	?>
	
</script>
