<link rel="stylesheet" type="text/css" href="<?php echo $tplPath;?>/public/DatePicker/skin/WdatePicker.css" />
<script type="text/javascript" src="<?php echo $tplPath;?>/public/DatePicker/WdatePicker.js"></script>
<div id="editFileContainer">
	<div class="modal-header"></div>
	<div class="modal-body" id="editFileInfoOtherPropDiv">
	
	<?php echo $html;?>
	</div>
	<div class="modal-footer">
	</div>
</div>

<style>
.editFileInfoHeight25px{
	height:25px;
}
.editFileInfoTitle{
	float:left;width:180px;
}
.editFileInfoValue{
	float:left;
}
</style>
