<style>
.fileditNew {
	width: 100%;
	height: 115px;
	float: left;
	border-left: 1px solid #ccc;
	border-bottom: 1px solid #ccc;
}

.fileditdivNew {
	width: 250px;
	height: 25px;
	float: left;
	margin-left: 10px;
	padding: 5px 20px 5px 20px;
}

.fileditdivNew input {
	width: 150px;
}

.fileditdivAreaNew {
	width: 250px;
	height: 68px;
	float: left;
	margin-left: 50px;
	padding: 5px 20px 5px 20px;
}

.filednameNew {
	width: 60px;
	line-height: 25px;
	text-indent: 5px;
	float: left;
}

.filedvalueNew {
	width: 60px;
	height: 25px;
	float: left
}
</style>
<div id='tempEmail' style="height: 30px;">
	<form id="addEmailAutoForm" action=""	method="post">
		<div class='fileditdivNew'>
			<p class='filednameNew'>&nbsp;邮箱：</p>
			<p class='filedvalueNew'>
				<input class='input' type="text" id="emailAutoInput" name="email"  verify="email/100/1/0"/>
		
		</div>
		<div class='fileditdivNew'>
			<p class='filednameNew'>&nbsp;密码：</p>
			<p class='filedvalueNew'>
				<input class='input' type='password' id="password" name="password" verify="text/50/1/0"></input>
		
		</div>
	</form>
</div>
<script type="text/javascript">

$("#password").blur(function(){
	if($("#password").val() == null || $("#password").val()==''){
		$("#password").addClass("invalid-text").attr("title","密码不能为空");
	}else{
		$("#password").removeClass("invalid-text").attr("title","");
	}
});

$("#emailAutoInput").blur(function(){
	var reg_mailType=/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/;
	var reg_result = reg_mailType.test(this.value);
	if(!reg_result ){
		$("#emailAutoInput").addClass("invalid-text").attr("title","请输入合法的邮箱");
	}else if($("#emailAutoInput").val() == null || $.trim($("#emailAutoInput").val())==''){
		$("#emailAutoInput").addClass("invalid-text").attr("title","此项不能为空");	
	}else{
		$("#emailAutoInput").removeClass("invalid-text").attr("title","");
	}
});
	
</script>
