<style>
/*可编辑的下拉框*/
.editSelect .selectInputSpan {
	/* width: 364px; */
height: 26px;
float: left;
border: 0pt;
font-size: 9pt;
padding: 0px;
margin: 0px;
background-color: white;
	
}
.inputtext2 {
	MARGIN-LEFT: 5px;
height: 22px;
border: 1px solid #A69F9F;
background-repeat: no-repeat;
background-position: 99% 50%;
}

.editSelect .selectSpan{
border-top-style: solid;
border-right-style: solid;
border-bottom-style: solid;
border-top: 1pt solid #B5A9A9;
border-right: 1pt solid #B5A9A9;
border-bottom: 1pt solid #B5A9A9;
overflow: hidden;
width: 17px;
height: 20px;
float: left;
clip: rect(-1px, 384px, 384px, 364px);

	
}
.editSelect .selectSpan select{
	width: 267px !important;
	height: 22px !important;
	border: 0pt !important;
	margin: 0px 0px 0px -247px !important;
}
.orglable {float:left;}
.addMsg{
	color:rgb(102, 102, 102);
}
#editUserForm{
	max-height:300px;
	overflow-y:auto;
	width:400px;
	padding:20px 10px 5px 10px;
}
.useritem{
	height:110px;
}
.useritemchild{
	width:100%;
	height:100%;
	position: relative;
	padding:20px 5px 5px 5px;
}
.userdivover{
	background:#f7f7f7;
	-webkit-box-shadow: 0 2px 10px rgba(64,54,63,0.5);
  	-moz-box-shadow: 0 2px 10px rgba(64,54,63,0.5);
  	box-shadow: 0 2px 10px rgba(64,54,63,0.5);
  	border-radius: 4px;
}
.closeUserButton {
	width:16px;
	height:16px;
	line-height:16px;
	position: absolute; 
	right: 2px;
	top: -10px;
	color:#ffffff;
	text-align:center;
	cursor: pointer;
	background: url(<?php echo $tplPath?>/ESUserInfo/img/removes.png) no-repeat; 
}
.closeUserButton:hover {background-position-x: -16px;}
.titUse{
	float:left;width:80px;text-align:right;margin:4px 0 0 0;font-size:14px;
}
.inpDiv{
	float:left;margin-left:5px;
}
.lineDiv{
	clear: both; height: 10px;
}
.inputUse{
	width: 260px; height: 20px;
}
</style>
<form id="editUserForm" method="post" enctype="multipart/form-data">
	<input id="editUserid" name="editUserid" value="<?php echo $userinfo['ID'];?>" type="hidden">
	<input id="editCompid" name="editCompid" value="<?php echo $userinfo['COMPID'];?>" type="hidden">
	<div id="team_1" class="useritem">
		<div class="useritemchild" style="padding:5px;">
			
			<div class="closeUserButton" id="deleteicon1" style="display: none"></div>
			<label class="titUse">用户名:</label>
			<div class="inpDiv" id="editUsernameDiv">
				<input type="text" id="editUsername" name="editUsername" maxLength="50"  class="inputUse"  readonly="readonly" value="<?php echo $userinfo['USERNAME'];?>"/>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">姓名:</label>
			<div class="inpDiv" id="editFullnameDiv">
				<input type="text" id="editFullname" name="editFullname" maxLength="50"  class="inputUse"  value="<?php echo $userinfo['FULLNAME'];?>"/>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">机构:</label>
			<div class="editSelect">
				<div class="selectInputSpan" id="editOrgnameDiv">
					<input type="text" name="editOrgname" id="editOrgname" class="inputtext2" value="<?php echo $userinfo['ORGNAME']==""?"编辑此处添加新机构":$userinfo['ORGNAME'];?>" verify="unspecial/50/1/0"  style="width: 245px; height: 20px;">
				</div>
				<div class="selectSpan">
					<select  onchange="inputshow(this);" name="org" class="org">
					<option value="-1">编辑此处添加新机构</option>
						 <?php foreach ($success as $k=>$val) { ?>
											<option value="<?php echo $val->id;?>" <?php echo $val->id == $userinfo['ORGID'] ? "selected=selected":"";?>><?php echo $val->orgname;?></option>
						 <?php };?>
					</select>
				</div>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">手机号:</label>
			<div class="inpDiv" id="editMobilephoneDiv">
				<input type="text" id="editMobilephone" name="editMobilephone" maxLength="50"  class="inputUse"  value="<?php echo $userinfo['MOBILEPHONE'];?>"/>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">公司电话:</label>
			<div class="inpDiv" id="editTelephoneDiv">
				<input type="text" id="editTelephone" name="editTelephone" maxLength="50"  class="inputUse"  value="<?php echo $userinfo['TELEPHONE'];?>"/>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">Email:</label>
			<div class="inpDiv" id="editEmailDiv">
				<input type="text" id="editEmail" name="editEmail" maxLength="50"  class="inputUse"  value="<?php echo $userinfo['EMAIL'];?>"/>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">职位:</label>
			<div class="inpDiv" id="editPositionDiv">
				<input type="text" id="editPosition" name="editPosition" maxLength="50"  class="inputUse"  value="<?php echo $userinfo['POSITION'];?>"/>
			</div>
			<div class="lineDiv"></div>
			<label class="titUse">传真地址:</label>
			<div class="inpDiv" id="editFaxDiv">
				<input type="text" id="editFax" name="editFax" maxLength="50"  class="inputUse"  value="<?php echo $userinfo['FAX'];?>"/>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript">
function inputshow(obj){
	var checkText=$(".org").find("option:selected").text();
	$(obj).parent().parent().find('input').val(checkText);
}


(function ($) {
	$("#editUserForm").on("mouseover", '.useritem', function(){
		if('team_1' != $(this).attr("id"))$(this).find(".closeUserButton").css("display", "block") ;
	});
	$('#editUserForm').on("mouseout", ".useritem", function(){
		if('team_1' != $(this).attr("id"))$(this).find(".closeUserButton").css("display", "none") ;
	});
	$('#editUserForm').on("click", ".closeUserButton", function(){
		 $(this).parent().parent().remove();
	});

	//正则
	var nameZZ= /^[\u4e00-\u9fa5a-zA-Z]+$/;
	var unameZZ= /^[a-zA-Z]+$/;
	var mobtelZZ =/^1[3|4|5|8][0-9]\d{8}$/;
	var teleZZ = /^(0[0-9]{2,3}-)?([2-9][0-9]{6,7})+(-[0-9]{1,4})?$/;
	var emailaddressZZ = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	var fexZZ =/^(([0\+]\d{2,3}-)?(0\d{2,3})-)(\d{7,8})(-(\d{3,}))?$/; 
	
	$('#editFullname').live("blur", function(){
	 	var editFullname = $(this).val();
	 	editFullname=editFullname.replace(/[ ]/g,"");
	 	if(editFullname==''){
	 		$("#editFullnameDiv").showTooltips("姓名不能为空！", 5000) ;
	 		return;
	 	} else if(nameZZ.test(editFullname)==false){
	 		$("#editFullnameDiv").showTooltips("姓名只能包含中文和英文字符!", 5000) ;
	 		return;
	 	}
	});
	
	$('#editEmail').live("blur", function(){
	 	var editEmail = $(this).val();
	 	editEmail=editEmail.replace(/[ ]/g,"");
	 	if(editEmail==''){
	 		$("#editEmailDiv").showTooltips("激活邮箱不能为空!", 5000) ;
	 		return;
	 	}
	 	if(emailaddressZZ.test(editEmail)==false){
	 		$("#editEmailDiv").showTooltips("邮箱格式不正确!", 5000) ;
	 		return;
	 	}
	});
	$('#editUserForm').on("change", ".org", function(){
	 	var org = $(this).val();
	 	if(org!=''){
	 		$("#editOrgnameDiv").find("input").val(org);
	 	}
	});
	$('#editOrgname').live("blur", function(){
	 	var editOrgname = $(this).val();
	 	if(editOrgname==''){
	 		$("#editOrgnameDiv").showTooltips("请选择或输入用户所属机构！", 5000) ;
	 		return;
	 	}
	});
	$("#editMobilephone").live('blur',function(){
	 	var editMobilephone = $(this).val();
	 	editMobilephone=editMobilephone.replace(/[ ]/g,"");
	 	/* if(editMobilephone==''){
	 		$("#editMobilephoneDiv").showTooltips("手机号码不能为空!", 5000) ;
	 		return;
	 	} */
	 	if(mobtelZZ.test(editMobilephone)==false){
	 		$("#editMobilephoneDiv").showTooltips("手机号码格式不正确!", 5000) ;
	 		return;
	 	}
	});
	$("#editTelephone").live('blur',function(){
	 	var editTelephone = $(this).val();
	 	editTelephone=editTelephone.replace(/[ ]/g,"");
	 	/* if(editTelephone==''){
	 		$("#editTelephoneDiv").showTooltips("公司电话不能为空!", 5000);
	 		return;
	 	} */
	 	if(teleZZ.test(editTelephone)==false){
	 		$("#editTelephoneDiv").showTooltips("公司电话格式不正确!", 5000);
	 		return;
	 	}
	});
	$("#editFax").live('blur',function(){
	 	var editFax = $(this).val();
	 	editFax=editFax.replace(/[ ]/g,"");
	 	/* if(editFax==''){
	 		$("#editFaxDiv").showTooltips("传真不能为空!", 5000);
	 		return;
	 	} */
	 	if(fexZZ.test(editFax)==false){
	 		$("#editFaxDiv").showTooltips("传真格式不正确!", 5000);
	 		return;
	 	}
	});
	
})
</script>