<script type="text/javascript" src="<?php echo $tplPath;?>/ESUserInfo/js/import.js"></script>
<style>
	.userGridMain {
		width : 780px;
		height: 500px;
		overflow:hidden;
	}
	.userGridMain .bbar{
		position: absolute;
  		top: 88%;
	}
	.userGridMain .bbar dl{
		padding:0px;
		float:left;
		border:0px;
		height: 30px;
		background-color:#ffffff;
	}
	.userGridMain .bbar dd{
		float:left;
		margin-right:8px;
		cursor: pointer;
		height: 30px;
		padding-top:7px;
		padding-bottom:7px;
		width:16px;
		height:16px;
	}
	.userGridMain .bbar div{
		width:16px;
		height:16px;
	}
	.userGridList	{
		width : 780px;
		height: 450px;
		overflow:auto;
		border-top:1px solid #F0F0F0;
		border-bottom:1px solid #F0F0F0;
	}
	#userGridStep2	{
		width : 760px;
		height: 100%;
		overflow:auto;
	}
	#userGridStep2 .hover{
		background-color:#ffc;
		color:#0066CC;
		cursor: default;
	}
	#userGridStep2 table {
		width: 100%; 
		border-right:1px solid #F0F0F0;
		border-bottom:1px solid #F0F0F0;
	}
	#userGridStep2 table th{
		border-left:1px solid #F0F0F0;
		height:20px;
		padding:2px;
		text-align:center;
		font-weight:normal;
	} 
	#userGridStep2 table td{
		border-left:1px solid #F0F0F0;
		border-top:1px solid #F0F0F0;
		height:20px;
		padding:2px;
	} 
	.userGridMain .bbar .pFirst {
		background: url(<?php echo $tplPath?>/ESUserInfo/img/first.gif) no-repeat center;
	}
	
	.userGridMain .bbar .pPrev {
		background: url(<?php echo $tplPath?>/ESUserInfo/img/prev.gif) no-repeat center;
	}
	
	.userGridMain .bbar .pNext {
		background: url(<?php echo $tplPath?>/ESUserInfo/img/next.gif) no-repeat center;
	}
	
	.userGridMain .bbar .pLast {
		background: url(<?php echo $tplPath?>/ESUserInfo/img/last.gif) no-repeat center;
	}
	.inputUse {
		width:80px; 
		text-align:center;
	}
	
	#nowPageStep2 {
		border:1px solid #6F6E81;
		height:16px;
		padding: 1px 4px;
	}
</style>
<script id="userGridStep2Template" type="text/html">
	{{if total>0}}
		<table border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th>序号</th>
				<th>用户姓名</th>
                <th>邮箱</th>
				<th>公司电话</th>
				<th>手机</th>
				<th>传真</th>
				<th>职位</th>
			</tr>
			{{each lists as row i}}
				<tr>
					<td style="text-align:center;">{{=row.startNo+i}}</td>
					<td id="name_{{i}}"><input type="text" value="{{row.FULLNAME}}" name="fullNameImport"></td>
					<td id="email_{{i}}"><input type="text" value="{{row.EMAIL}}" name="emailImport"></td>
					<td><input type="text" class="inputUse" value="{{row.MOBILEPHONE}}" name="mobilephoneImport"></td>
					<td><input type="text" class="inputUse" value="{{row.TELEOHONE}}" name="teleohoneImport"></td>
					<td><input type="text" class="inputUse" value="{{row.FAX}}" name="faxImport"></td>
					<td><input type="text" class="inputUse" value="{{row.POSITION}}" name="positionImport"></td>
				</tr>
			{{/each}}
		</table>
    {{else}}
             <span style="padding: 20px;">无数据！</span>

	{{/if}}
</script>
<div class="userGridMain">
	<div class="tbar" id="userGridTbar">
		 <span id="titleshow"></span>
	</div>
	<input type="hidden" id="total" value=""/>
	<input type="hidden" id="endNo" value=""/>
	<input type="hidden" id="isImport" value=""/>
	<div class="userGridList">
		<div id="userGridStep2">
		</div>
	</div>
	<div class="bbar">
		<dl>
			<dd><div class="pFirst" title="首页"></div></dd>
			<dd><div class="pPrev" title="上一页"></div></dd>
			<dd><span id="nowPageStep2">1</span></dd>
			<dd><div class="pNext" title="下一页"></div></dd>
			<dd><div class="pLast" title="最后一页"></div></dd>
			<dd id="pReloadMsgStep2"  style="width:140px;text-align:left;visibility:hidden;">正在加载，请稍候...</dd>
			<dd id="bbarMsgStep2" style="width:400px;cursor: default;text-align:right;"></dd>
		</dl>
	</div>
</div>

<script type="text/javascript">
	var nameZZ= /^[\u4e00-\u9fa5a-zA-Z]+$/;
	var unameZZ= /^[a-zA-Z]+$/;
	var mobtelZZ =/^1[3|4|5|8][0-9]\d{8}$/;
	var teleZZ = /^(0[0-9]{2,3}-)?([2-9][0-9]{6,7})+(-[0-9]{1,4})?$/;
	var emailaddressZZ = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	var fexZZ =/^(([0\+]\d{2,3}-)?(0\d{2,3})-)(\d{7,8})(-(\d{3,}))?$/; 
(function ($) {
    $("#titleshow").text("未导入，请检查导入的数据是否正确！");
	setp2Template(1) ;
	function setp2Template(nowPageStep2){
		$("#pReloadMsgStep2").css("visibility", "visible") ;
		$.ajax({
		    url : $.appClient.generateUrl({ESUserInfo : 'initImportStep2ByPage'},'x'),
		    type : 'POST',
		    data : {nowPageStep2:nowPageStep2},
		    dataType:"json",
		    success:function(json){
				$('#userGridStep2').html(template('userGridStep2Template', json));
				$("#bbarMsgStep2").html("显示 " + json.startNo + " 到 " + json.endNo + " 条 / 共" + json.total + "条");
				$('#nowPageStep2').attr("pageCount", json.pageCount);
				$("#pReloadMsgStep2").css("visibility", "hidden") ;
				$("#total").val(json.total) ;
				$("#endNo").val(json.endNo) ;
				if(json.isImport=="true"){
					$("#titleshow").text("当前页已成功导入！");
					$("#isImport").val("true");
				}else{
					$("#btnImport").next().remove();
					$("#btnImport").after("<button type='button' id='verMun' >关闭</button>");
					$('#verMun').on('click',function(){
						$.dialog({
							content : '还有未导入页,确定关闭吗？',
							okVal : '确定',
							ok : true,
							cancelVal : '取消',
							cancel : true,
							ok : function() {
								//关闭导入页
							    art.dialog.list["importStep2"].close();
							    //刷新列表
								closeWin();
							   }
							});
					});	
					
					$("#titleshow").text("未导入，请检查导入的数据是否正确！");
					$("#isImport").val("false");
				}
		    }
		});
	}

	/** 鼠标经过行颜色改变监听 **/
	$('#userGridStep2').on('mouseover', "tr", function(){
		$(this).children("td").addClass("hover") ;
	}) ;
	$('#userGridStep2').on('mouseout', "tr", function(){
		$(this).children("td").removeClass("hover") ;
	}) ;
	$(".bbar").on("mouseover", "div", function(){
		$(this).css("border", "1px solid #FFFFFF");
	});
	$(".bbar").on("mouseout", "div", function(){
		$(this).css("border", "");
	});
	$(".bbar").on("click", "div", function(){
		if($(this).attr("class") == "pFirst"){
			if($('#nowPageStep2').html()*1>1){
				setp2Template(1) ;
				$('#nowPageStep2').html(1) ;
			}
		} else if($(this).attr("class") == "pPrev"){
			if($('#nowPageStep2').html()*1>1){
				var newpage = $('#nowPageStep2').html()*1-1 ;
				setp2Template(newpage) ;
				$('#nowPageStep2').html(newpage) ;
			}
		} else if($(this).attr("class") == "pNext"){
			if(parseInt($('#total').val()) > parseInt($('#endNo').val())){
				var newpage = $('#nowPageStep2').html()*1+1 ;
				setp2Template(newpage) ;
				$('#nowPageStep2').html(newpage) ;
			}
		} else if($(this).attr("class") == "pLast"){
			if($('#nowPageStep2').attr("pageCount")*1>$('#nowPageStep2').html()*1){
				var newpage = parseInt($('#total').val()/$('#nowPageStep2').attr("pageCount"))+1;
				setp2Template(newpage) ;
				$('#nowPageStep2').html(newpage) ;
			}
		} 
	});
	$(".tbar").on("mouseover", "dd", function(){
		$(this).css("background-color", "#133959");
	});
	$(".tbar").on("mouseout", "dd", function(){
		$(this).css("background-color", "#6F6E81");
	});
})(jQuery);
</script>