<link href='<?php echo $tplPath?>/ESUserInfo/css/active.css' rel="stylesheet" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<script type="text/javascript" src="/js/jquery.js"></script>
<script	type="text/javascript" src="<?php echo $tplPath;?>/public/js/jquery.appclient.js?baseurl=<?php echo $esaction->generateUrl(array());?>"></script>
<header class="headerheader">
					<a href="http://www.flyingsoft.cn/" id="header_logo"><img src="<?php echo $tplPath?>/ESUserInfo/img/flyingsoftlogo.png" width="150" height="70"/></a>
		
	</header>

<div id="page">

		<div id="page_contents" >

		<div class="col span_4_of_6 margin_auto float_none" >
			<p class="alerterror alert_error"  id="alerterror" isAccounted="false" style="display:none">
		<!-- 		<i class="fa fa-warning"></i>  -->
			</p>
		</div>
<div class="card col span_4_of_6 margin_auto float_none right_padding">

	<h1 class="align_center">欢迎来到东方飞扬</h1>

	<p class="align_center large_bottom_margin">尊敬的 <strong><?php echo $_GET['fullname'];?></strong> 填写您的新密码完成重置。</p>


	<form   class="col span_4_of_6 margin_auto float_none">
		<input type="hidden" name="fullname" id="fullname" value="<?php echo $_GET['fullname'];?>" />
		<input type="hidden" name="userid" id="userid" value="<?php echo $_GET['id'];?>" />
		<input type="hidden" name="companyid" id="companyid" value="<?php echo $_GET['companyid'];?>" />
		<input type="hidden" name="email" id="email" value="<?php echo $_GET['email'];?>" />
<!-- 		<input type="hidden" name="signup" value="1" /> -->
<!-- 		<input type="hidden" name="crumb" value="s-1425887392-d7b0d97d69-☃" /> -->

		<p class="">
			<label for="fullname">用户名</label>
			<input type="text" id="username" name="username" class="username_field" disabled="disabled" value="<?php echo $_GET['username'];?>" maxlength="21"/>
			<!-- <span class="input_note block small_bottom_margin">用户名必须是符合邮箱格式的字符串.</span> -->
			<!-- 	<span class="input_note">您可以使用您的激活邮箱或其他邮箱，也可以使用类似邮箱格式的字符串.</span> -->
		</p>
		<div class="col span_6_of_6 float_none" >
			<p class="alerterror alert_error" id="usernamealerterror" style="display:none">
			</p>
		</div>

		<p class=" large_bottom_margin">
			<label for="password">新密码</label>
			<input type="password" id="password" name="password"/>
		</p>
		<div class="col span_6_of_6 float_none" >
			<p class="alerterror alert_error" id="passwordalerterror" style="display:none">
			</p>
		</div>
		<p class=" large_bottom_margin">
			<label for="repassword">确认密码</label>
			<input type="password" id="repassword" name="repassword" />
			<!-- <span class="input_note block small_bottom_margin">请再次输入密码，确保密码正确无误.</span> -->
		</p>
		<div class="col span_6_of_6 float_none" >
			<p class="alerterror alert_error" id="repasswordalerterror" style="display:none">
			</p>
		</div>
		<p>
			
		</p>


		<p class="large_bottom_margin" style="margin-left: 20px;"><button type="button" id="toforgetpassword"" class="btn btn_large full_width ladda-button" ><span class="ladda-label">重置</span></button></p>

		<p class="legalese small_bottom_margin" align="center">聚焦客户关注的挑战和压力，提供有竞争力的文档信息资源内容管理解决方案和服务，持续为客户创造最大价值.</p>

	</form>

</div>


		
	</div>
	<div id="overlay"></div>
</div>

<script type="text/javascript">
$('#password').on("blur", function(){
	if($("#alerterror").attr('isAccounted') == "true"){
		return ;
	}
	var password = $(this).val();
	if($.trim(password)==''){
		$("#passwordalerterror").html("密码不能为空!");
		$("#passwordalerterror").css('display','block');
	} else if($.trim($("#repassword").val())==$.trim(password)){
		$("#repasswordalerterror").css('display','none');
		$("#passwordalerterror").css('display','none');
	} else {
		$("#passwordalerterror").css('display','none');
	}
});

$('#repassword').on("blur", function(){
	if($("#alerterror").attr('isAccounted') == "true"){
		return ;
	}
	var repassword = $(this).val();
	if($.trim(repassword)==''){
		$("#repasswordalerterror").html("确认密码不能为空!");
		$("#repasswordalerterror").css('display','block');
	} else if($.trim($("#password").val())!=$.trim(repassword)){
		$("#repasswordalerterror").html("您两次输入的密码不一致，请重新输入!");
		$("#repasswordalerterror").css('display','block');
	} else {
		$("#repasswordalerterror").css('display','none');
	}
});
var url = $.appClient.generateUrl({ESUserInfo:'toforgetpassword1'},'x');
$.ajax({
	url:url,
	type:'POST',
	data:{id:$("#userid").val(),companyid:$("#companyid").val(),username:$('#username').val(),email:$('#email').val()},
	success:function(data){
		var success = $.parseJSON(data);
		if(success.timeout){
			$("#alerterror").append("已超出修改时间！");
			$("#alerterror").css('display','block');
			$("#alerterror").attr('isAccounted','true');
			$("#toforgetpassword").css("background-color", "#E8E8E8");
			$("#toforgetpassword").css("cursor", "default;");
		}
	}
});

$('#toforgetpassword').on('click',function(){
	if($("#alerterror").attr('isAccounted') == "true"){
		return ;
	}
	var url = $.appClient.generateUrl({ESUserInfo:'fromforgetpasswordtochange'},'x');
	$.ajax({
		url:url,
		type:'POST',
		data:{id:$("#userid").val(),companyid:$("#companyid").val(),username:$('#username').val(),email:$('#email').val(),password:$('#password').val()},
		success:function(data){
			var success = $.parseJSON(data);
			if(success.success){
				alert("修改成功");
			}
		}
	});
});
</script>